// registry/components/pagination/vue/Pagination.vue
<script setup lang="ts">
import { computed } from "vue";

const props = withDefaults(
  defineProps<{
    page?: number;
    pageCount: number;
    total?: number;
    pageSize?: number;
    /** Rows-per-page options; renders a selector when provided. */
    pageSizeOptions?: number[];
    siblingCount?: number;
    showSummary?: boolean;
  }>(),
  {
    page: 1,
    total: undefined,
    pageSize: undefined,
    pageSizeOptions: undefined,
    siblingCount: 1,
    showSummary: false,
  }
);

const emit = defineEmits<{
  "update:page": [page: number];
  change: [page: number];
  "update:pageSize": [size: number];
  pageSizeChange: [size: number];
}>();

function onSize(e: Event) {
  const size = Number((e.target as HTMLSelectElement).value);
  emit("update:pageSize", size);
  emit("pageSizeChange", size);
}

function go(p: number) {
  if (p >= 1 && p <= props.pageCount && p !== props.page) {
    emit("update:page", p);
    emit("change", p);
  }
}

const pages = computed<(number | "…")[]>(() => {
  const current = props.page;
  const total = props.pageCount;
  const siblings = props.siblingCount;
  const span = siblings * 2 + 5;
  if (total <= span) return Array.from({ length: total }, (_, i) => i + 1);
  const left = Math.max(current - siblings, 1);
  const right = Math.min(current + siblings, total);
  const out: (number | "…")[] = [1];
  if (left > 2) out.push("…");
  for (let p = Math.max(left, 2); p <= Math.min(right, total - 1); p++) out.push(p);
  if (right < total - 1) out.push("…");
  out.push(total);
  return out;
});

const hasSummary = computed(() => props.total != null && props.pageSize != null);
const from = computed(() => (hasSummary.value ? (props.page - 1) * props.pageSize! + 1 : 0));
const to = computed(() => (hasSummary.value ? Math.min(props.page * props.pageSize!, props.total!) : 0));
</script>

<template>
  <nav class="jl-pagination" aria-label="Pagination">
    <div v-if="showSummary && hasSummary" class="jl-pagination__summary">
      <b>{{ from.toLocaleString() }}–{{ to.toLocaleString() }}</b> of <b>{{ total!.toLocaleString() }}</b>
    </div>
    <div v-if="showSummary" class="jl-pagination__spacer" />
    <div class="jl-pagination__list">
      <button
        type="button"
        class="jl-page jl-page--arrow"
        aria-label="Previous page"
        :disabled="page <= 1"
        @click="go(page - 1)"
      >
        <svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m15 6-6 6 6 6" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" /></svg>
      </button>
      <template v-for="(p, i) in pages" :key="typeof p === 'number' ? p : `e${i}`">
        <span v-if="p === '…'" class="jl-page jl-page--ellipsis" aria-hidden="true">…</span>
        <button
          v-else
          type="button"
          class="jl-page"
          :aria-current="p === page ? 'page' : undefined"
          :aria-label="`Page ${p}`"
          @click="go(p)"
        >
          {{ p }}
        </button>
      </template>
      <button
        type="button"
        class="jl-page jl-page--arrow"
        aria-label="Next page"
        :disabled="page >= pageCount"
        @click="go(page + 1)"
      >
        <svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m9 6 6 6-6 6" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" /></svg>
      </button>
    </div>
    <label v-if="pageSizeOptions && pageSizeOptions.length" class="jl-pagination__size">
      <span>Rows</span>
      <select :value="pageSize" aria-label="Rows per page" @change="onSize">
        <option v-for="n in pageSizeOptions" :key="n" :value="n">{{ n }}</option>
      </select>
    </label>
  </nav>
</template>

<style src="./pagination.css"></style>

// registry/components/pagination/react/pagination.tsx
import * as React from "react";
import "./pagination.css";

export interface PaginationProps
  extends Omit<React.HTMLAttributes<HTMLElement>, "onChange"> {
  page?: number;
  pageCount: number;
  total?: number;
  pageSize?: number;
  /** Rows-per-page options; renders a selector when provided. */
  pageSizeOptions?: number[];
  /** Fires when a new page size is chosen. */
  onPageSizeChange?: (size: number) => void;
  siblingCount?: number;
  showSummary?: boolean;
  onChange?: (page: number) => void;
}

function pageList(current: number, total: number, siblings: number): (number | "…")[] {
  const span = siblings * 2 + 5;
  if (total <= span) return Array.from({ length: total }, (_, i) => i + 1);
  const left = Math.max(current - siblings, 1);
  const right = Math.min(current + siblings, total);
  const showLeftDots = left > 2;
  const showRightDots = right < total - 1;
  const out: (number | "…")[] = [1];
  if (showLeftDots) out.push("…");
  for (let p = Math.max(left, 2); p <= Math.min(right, total - 1); p++) out.push(p);
  if (showRightDots) out.push("…");
  out.push(total);
  return out;
}

function Arrow({ dir }: { dir: "left" | "right" }) {
  return (
    <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path
        d={dir === "left" ? "m15 6-6 6 6 6" : "m9 6 6 6-6 6"}
        stroke="currentColor"
        strokeWidth="1.9"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

export function Pagination({
  page = 1,
  pageCount,
  total,
  pageSize,
  pageSizeOptions,
  onPageSizeChange,
  siblingCount = 1,
  showSummary = false,
  onChange,
  className = "",
  ...rest
}: PaginationProps) {
  const go = (p: number) => {
    if (p >= 1 && p <= pageCount && p !== page && onChange) onChange(p);
  };
  const pages = pageList(page, pageCount, siblingCount);

  const from = total != null && pageSize != null ? (page - 1) * pageSize + 1 : null;
  const to = total != null && pageSize != null ? Math.min(page * pageSize, total) : null;

  return (
    <nav
      className={["jl-pagination", className].filter(Boolean).join(" ")}
      aria-label="Pagination"
      {...rest}
    >
      {showSummary && from != null && (
        <div className="jl-pagination__summary">
          <b>
            {from.toLocaleString()}–{to!.toLocaleString()}
          </b>{" "}
          of <b>{total!.toLocaleString()}</b>
        </div>
      )}
      {showSummary && <div className="jl-pagination__spacer" />}
      <div className="jl-pagination__list">
        <button
          type="button"
          className="jl-page jl-page--arrow"
          aria-label="Previous page"
          disabled={page <= 1}
          onClick={() => go(page - 1)}
        >
          <Arrow dir="left" />
        </button>
        {pages.map((p, i) =>
          p === "…" ? (
            <span key={`e${i}`} className="jl-page jl-page--ellipsis" aria-hidden="true">
              …
            </span>
          ) : (
            <button
              key={p}
              type="button"
              className="jl-page"
              aria-current={p === page ? "page" : undefined}
              aria-label={`Page ${p}`}
              onClick={() => go(p)}
            >
              {p}
            </button>
          )
        )}
        <button
          type="button"
          className="jl-page jl-page--arrow"
          aria-label="Next page"
          disabled={page >= pageCount}
          onClick={() => go(page + 1)}
        >
          <Arrow dir="right" />
        </button>
      </div>
      {pageSizeOptions && pageSizeOptions.length > 0 && (
        <label className="jl-pagination__size">
          <span>Rows</span>
          <select
            value={pageSize}
            onChange={(e) => onPageSizeChange?.(Number(e.target.value))}
            aria-label="Rows per page"
          >
            {pageSizeOptions.map((n) => (
              <option key={n} value={n}>
                {n}
              </option>
            ))}
          </select>
        </label>
      )}
    </nav>
  );
}
