// registry/components/divider/react/divider.tsx
import * as React from "react";
import "./divider.css";

export type DividerOrientation = "horizontal" | "vertical";

export interface DividerProps extends React.HTMLAttributes<HTMLElement> {
  orientation?: DividerOrientation;
  label?: React.ReactNode;
}

const Divider = React.forwardRef<HTMLElement, DividerProps>(
  ({ orientation = "horizontal", label, className = "", ...props }, ref) => {
    if (label) {
      return (
        <div
          ref={ref as React.Ref<HTMLDivElement>}
          className={["jl-divider", "jl-divider--labeled", className]
            .filter(Boolean)
            .join(" ")}
          role="separator"
          {...props}
        >
          {label}
        </div>
      );
    }

    const isVertical = orientation === "vertical";
    return (
      <hr
        ref={ref as React.Ref<HTMLHRElement>}
        className={[
          "jl-divider",
          isVertical ? "jl-divider--v" : "jl-divider--h",
          className,
        ]
          .filter(Boolean)
          .join(" ")}
        role="separator"
        aria-orientation={isVertical ? "vertical" : undefined}
        {...props}
      />
    );
  }
);

Divider.displayName = "Divider";

export { Divider };

// registry/components/divider/vue/Divider.vue
<script setup lang="ts">
import { useSlots } from "vue";

type DividerOrientation = "horizontal" | "vertical";

const props = withDefaults(
  defineProps<{
    orientation?: DividerOrientation;
    label?: string;
  }>(),
  { orientation: "horizontal" }
);

const slots = useSlots();
const hasLabel = () => props.label != null || slots.default != null;
const isVertical = () => props.orientation === "vertical";
</script>

<template>
  <div
    v-if="hasLabel()"
    class="jl-divider jl-divider--labeled"
    role="separator"
  >
    <slot>{{ props.label }}</slot>
  </div>
  <hr
    v-else
    class="jl-divider"
    :class="isVertical() ? 'jl-divider--v' : 'jl-divider--h'"
    role="separator"
    :aria-orientation="isVertical() ? 'vertical' : undefined"
  />
</template>

<style src="./divider.css"></style>
