// registry/components/resizable/vue/Resizable.vue
<script setup lang="ts">
import { ref, provide, computed, onMounted, type Ref } from "vue";

export interface ResizableCtx {
  horizontal: Ref<boolean>;
  sizes: Ref<number[]>;
  count: Ref<number>;
  register: (config: { defaultSize?: number; minSize?: number }) => number;
  startDrag: (e: PointerEvent, i: number) => void;
  onMove: (e: PointerEvent) => void;
  endDrag: (e: PointerEvent) => void;
  onKey: (e: KeyboardEvent, i: number) => void;
}

const props = withDefaults(
  defineProps<{ direction?: "horizontal" | "vertical" }>(),
  { direction: "horizontal" }
);

const emit = defineEmits<{ (e: "resize", sizes: number[]): void }>();

const horizontal = computed(() => props.direction === "horizontal");
const container = ref<HTMLElement | null>(null);
const configs: { defaultSize?: number; minSize?: number }[] = [];
const sizes = ref<number[]>([]);
const count = ref(0);

function register(config: { defaultSize?: number; minSize?: number }) {
  configs.push(config);
  count.value = configs.length;
  return configs.length - 1;
}

function mins() {
  return configs.map((c) => (c.minSize != null ? c.minSize : 8));
}

onMounted(() => {
  const explicit = configs.map((c) => (c.defaultSize != null ? c.defaultSize : null));
  const given = explicit.filter((v): v is number => v != null).reduce((a, b) => a + b, 0);
  const missing = explicit.filter((v) => v == null).length;
  const fill = missing > 0 ? (100 - given) / missing : 0;
  sizes.value = explicit.map((v) => (v != null ? v : fill));
});

let drag: { i: number; start: number; total: number; sizes: number[] } | null = null;

function startDrag(e: PointerEvent, i: number) {
  e.preventDefault();
  const rect = container.value!.getBoundingClientRect();
  const total = horizontal.value ? rect.width : rect.height;
  drag = { i, start: horizontal.value ? e.clientX : e.clientY, total, sizes: [...sizes.value] };
  document.body.setAttribute("data-jl-resizing", horizontal.value ? "x" : "y");
  const el = e.currentTarget as HTMLElement;
  el.setAttribute("data-dragging", "true");
  el.setPointerCapture?.(e.pointerId);
}

function onMove(e: PointerEvent) {
  if (!drag) return;
  const m = mins();
  const pos = horizontal.value ? e.clientX : e.clientY;
  let deltaPct = ((pos - drag.start) / drag.total) * 100;
  const a = drag.sizes[drag.i]!;
  const b = drag.sizes[drag.i + 1]!;
  deltaPct = Math.max(deltaPct, -(a - m[drag.i]!));
  deltaPct = Math.min(deltaPct, b - m[drag.i + 1]!);
  const next = [...drag.sizes];
  next[drag.i] = a + deltaPct;
  next[drag.i + 1] = b - deltaPct;
  sizes.value = next;
  emit("resize", next);
}

function endDrag(e: PointerEvent) {
  if (!drag) return;
  drag = null;
  document.body.removeAttribute("data-jl-resizing");
  (e.currentTarget as HTMLElement).removeAttribute("data-dragging");
}

function onKey(e: KeyboardEvent, i: number) {
  const step = 2;
  let dir = 0;
  if (e.key === (horizontal.value ? "ArrowRight" : "ArrowDown")) dir = 1;
  else if (e.key === (horizontal.value ? "ArrowLeft" : "ArrowUp")) dir = -1;
  if (!dir) return;
  e.preventDefault();
  const m = mins();
  const a = sizes.value[i]!;
  const b = sizes.value[i + 1]!;
  let delta = dir * step;
  delta = Math.max(delta, -(a - m[i]!));
  delta = Math.min(delta, b - m[i + 1]!);
  const next = [...sizes.value];
  next[i] = a + delta;
  next[i + 1] = b - delta;
  sizes.value = next;
  emit("resize", next);
}

provide<ResizableCtx>("jlResizable", {
  horizontal,
  sizes,
  count,
  register,
  startDrag,
  onMove,
  endDrag,
  onKey,
});
</script>

<template>
  <div ref="container" :class="['jl-resizable', `jl-resizable--${direction}`]">
    <slot />
  </div>
</template>

<style src="./resizable.css"></style>

// registry/components/resizable/react/resizable.tsx
/* eslint-disable react-refresh/only-export-components */
import * as React from "react";
import "./resizable.css";

export interface ResizablePanelProps extends React.HTMLAttributes<HTMLDivElement> {
  defaultSize?: number;
  minSize?: number;
}

export interface ResizableProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, "onResize"> {
  direction?: "horizontal" | "vertical";
  onResize?: (sizes: number[]) => void;
}

interface ResizableComposition {
  (props: ResizableProps): React.JSX.Element;
  Panel: (props: ResizablePanelProps) => null;
}

// marker component; the actual panel + handle are rendered by Resizable
function ResizablePanel(): null {
  return null;
}

interface DragState {
  i: number;
  start: number;
  total: number;
  sizes: number[];
}

function ResizableRoot({
  direction = "horizontal",
  className = "",
  onResize,
  children,
  ...rest
}: ResizableProps) {
  const horizontal = direction === "horizontal";
  const containerRef = React.useRef<HTMLDivElement>(null);
  const dragRef = React.useRef<DragState | null>(null);

  const panels = React.Children.toArray(children).filter((c) =>
    React.isValidElement(c)
  ) as React.ReactElement<ResizablePanelProps>[];
  const mins = panels.map((p) => (p.props.minSize != null ? p.props.minSize : 8));

  const [sizes, setSizes] = React.useState<number[]>(() => {
    const explicit = panels.map((p) => (p.props.defaultSize != null ? p.props.defaultSize : null));
    const given = explicit.filter((v): v is number => v != null).reduce((a, b) => a + b, 0);
    const missing = explicit.filter((v) => v == null).length;
    const fill = missing > 0 ? (100 - given) / missing : 0;
    return explicit.map((v) => (v != null ? v : fill));
  });

  const startDrag = (e: React.PointerEvent, i: number) => {
    e.preventDefault();
    const rect = containerRef.current!.getBoundingClientRect();
    const total = horizontal ? rect.width : rect.height;
    dragRef.current = {
      i,
      start: horizontal ? e.clientX : e.clientY,
      total,
      sizes: [...sizes],
    };
    document.body.setAttribute("data-jl-resizing", horizontal ? "x" : "y");
    e.currentTarget.setAttribute("data-dragging", "true");
    e.currentTarget.setPointerCapture?.(e.pointerId);
  };

  const onMove = (e: React.PointerEvent) => {
    const d = dragRef.current;
    if (!d) return;
    const pos = horizontal ? e.clientX : e.clientY;
    let deltaPct = ((pos - d.start) / d.total) * 100;
    const a = d.sizes[d.i];
    const b = d.sizes[d.i + 1];
    deltaPct = Math.max(deltaPct, -(a - mins[d.i]));
    deltaPct = Math.min(deltaPct, b - mins[d.i + 1]);
    const next = [...d.sizes];
    next[d.i] = a + deltaPct;
    next[d.i + 1] = b - deltaPct;
    setSizes(next);
    onResize?.(next);
  };

  const endDrag = (e: React.PointerEvent) => {
    if (!dragRef.current) return;
    dragRef.current = null;
    document.body.removeAttribute("data-jl-resizing");
    e.currentTarget.removeAttribute("data-dragging");
  };

  const onKey = (e: React.KeyboardEvent, i: number) => {
    const step = 2;
    let dir = 0;
    if (e.key === (horizontal ? "ArrowRight" : "ArrowDown")) dir = 1;
    else if (e.key === (horizontal ? "ArrowLeft" : "ArrowUp")) dir = -1;
    if (!dir) return;
    e.preventDefault();
    const a = sizes[i],
      b = sizes[i + 1];
    let delta = dir * step;
    delta = Math.max(delta, -(a - mins[i]));
    delta = Math.min(delta, b - mins[i + 1]);
    const next = [...sizes];
    next[i] = a + delta;
    next[i + 1] = b - delta;
    setSizes(next);
    onResize?.(next);
  };

  return (
    <div
      ref={containerRef}
      className={["jl-resizable", `jl-resizable--${direction}`, className].filter(Boolean).join(" ")}
      {...rest}
    >
      {panels.map((panel, i) => {
        const { className: pcls = "", style: pstyle, children: pchildren } = panel.props;
        const out: React.ReactNode[] = [
          <div
            key={`p-${i}`}
            className={["jl-resizable__panel", pcls].filter(Boolean).join(" ")}
            style={{ flexBasis: `${sizes[i]}%`, flexGrow: 0, flexShrink: 0, ...pstyle }}
          >
            {pchildren}
          </div>,
        ];
        if (i < panels.length - 1) {
          out.push(
            <div
              key={`h-${i}`}
              className="jl-resizable__handle"
              role="separator"
              tabIndex={0}
              aria-orientation={horizontal ? "vertical" : "horizontal"}
              aria-valuenow={Math.round(sizes[i])}
              onPointerDown={(e) => startDrag(e, i)}
              onPointerMove={onMove}
              onPointerUp={endDrag}
              onPointerCancel={endDrag}
              onKeyDown={(e) => onKey(e, i)}
            >
              <span className="jl-resizable__grip">
                <span />
                <span />
                <span />
              </span>
            </div>
          );
        }
        return out;
      })}
    </div>
  );
}

export const Resizable = Object.assign(ResizableRoot, {
  Panel: ResizablePanel,
}) as ResizableComposition;
