// registry/components/input/vue/Input.vue
<script setup lang="ts">
import { computed, useSlots } from "vue";

type InputSize = "sm" | "md" | "lg";

const props = withDefaults(
  defineProps<{
    size?: InputSize;
    invalid?: boolean;
    disabled?: boolean;
    modelValue?: string | number;
    /** Inline text before the field (e.g. "https://"). Or use the `prefix` slot. */
    prefix?: string;
    /** Inline text after the field (e.g. ".dev", a unit). Or use the `suffix` slot. */
    suffix?: string;
    /** Show a clear (×) button when the value is non-empty. @default false */
    clearable?: boolean;
  }>(),
  { size: "md", invalid: false, disabled: false, modelValue: "", prefix: undefined, suffix: undefined }
);

const emit = defineEmits<{
  "update:modelValue": [value: string];
  clear: [];
}>();

const slots = useSlots();

const showClear = computed(
  () => props.clearable && !props.disabled && props.modelValue != null && props.modelValue !== ""
);

function onInput(event: Event) {
  emit("update:modelValue", (event.target as HTMLInputElement).value);
}
function onClear() {
  emit("update:modelValue", "");
  emit("clear");
}
</script>

<template>
  <div
    class="jl-input-wrap"
    :class="`jl-input-wrap--${props.size}`"
    :data-invalid="props.invalid || undefined"
    :data-disabled="props.disabled || undefined"
  >
    <span v-if="slots.icon" class="jl-input-adorn"><slot name="icon" /></span>
    <span v-if="slots.prefix || props.prefix" class="jl-input-affix"><slot name="prefix">{{ props.prefix }}</slot></span>
    <input
      class="jl-input"
      :value="props.modelValue"
      :disabled="props.disabled"
      :aria-invalid="props.invalid || undefined"
      v-bind="$attrs"
      @input="onInput"
    />
    <button
      v-if="showClear"
      type="button"
      class="jl-input-clear"
      aria-label="Clear"
      tabindex="-1"
      @click="onClear"
    >
      <svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
        <path d="M4 4l8 8M12 4l-8 8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
      </svg>
    </button>
    <span v-if="slots.suffix || props.suffix" class="jl-input-affix"><slot name="suffix">{{ props.suffix }}</slot></span>
    <span v-if="slots.trailing" class="jl-input-adorn"><slot name="trailing" /></span>
  </div>
</template>

<style src="./input.css"></style>

// registry/components/input/react/input.tsx
import * as React from "react";
import "./input.css";

export type InputSize = "sm" | "md" | "lg";

export interface InputProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "size" | "prefix"> {
  size?: InputSize;
  /** Leading icon node. */
  icon?: React.ReactNode;
  /** Trailing node (icon, button, hint). */
  trailing?: React.ReactNode;
  /** Inline text/node before the field (e.g. "https://"). */
  prefix?: React.ReactNode;
  /** Inline text/node after the field (e.g. ".dev", a unit). */
  suffix?: React.ReactNode;
  /** Show a clear (×) button when the controlled value is non-empty. @default false */
  clearable?: boolean;
  /** Called when the clear button is pressed; defaults to emitting an empty-value change. */
  onClear?: (e: React.MouseEvent) => void;
  invalid?: boolean;
}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  (
    {
      size = "md",
      icon,
      trailing,
      prefix,
      suffix,
      clearable = false,
      onClear,
      invalid = false,
      disabled = false,
      value,
      onChange,
      className = "",
      ...props
    },
    ref
  ) => {
    const controlled = value !== undefined;
    const showClear =
      clearable && !disabled && controlled && value != null && value !== "";
    const clear = (e: React.MouseEvent) => {
      if (onClear) return onClear(e);
      onChange?.({
        ...e,
        target: { ...(e.target as HTMLInputElement), value: "" },
        currentTarget: { ...(e.currentTarget as HTMLInputElement), value: "" },
      } as unknown as React.ChangeEvent<HTMLInputElement>);
    };
    return (
      <div
        className={["jl-input-wrap", `jl-input-wrap--${size}`, className]
          .filter(Boolean)
          .join(" ")}
        data-invalid={invalid || undefined}
        data-disabled={disabled || undefined}
      >
        {icon && <span className="jl-input-adorn">{icon}</span>}
        {prefix && <span className="jl-input-affix">{prefix}</span>}
        <input
          ref={ref}
          className="jl-input"
          disabled={disabled}
          aria-invalid={invalid || undefined}
          value={value}
          onChange={onChange}
          {...props}
        />
        {showClear && (
          <button
            type="button"
            className="jl-input-clear"
            aria-label="Clear"
            onClick={clear}
            tabIndex={-1}
          >
            <svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
              <path d="M4 4l8 8M12 4l-8 8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
            </svg>
          </button>
        )}
        {suffix && <span className="jl-input-affix">{suffix}</span>}
        {trailing && <span className="jl-input-adorn">{trailing}</span>}
      </div>
    );
  }
);

Input.displayName = "Input";

export { Input };
