// registry/components/dropdown-menu/react/dropdown-menu.tsx
import * as React from "react";
import "./dropdown-menu.css";

export interface DropdownMenuProps {
  trigger: React.ReactElement;
  align?: "start" | "end";
  side?: "bottom" | "top";
  className?: string;
  children?: React.ReactNode;
}

export interface DropdownMenuItemProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  icon?: React.ReactNode;
  shortcut?: React.ReactNode;
  tone?: "default" | "danger";
  disabled?: boolean;
  onSelect?: (e: React.MouseEvent) => void;
}

const MenuCtx = React.createContext<{ close: () => void }>({ close: () => {} });

function DropdownMenuRoot({
  trigger,
  align = "start",
  side = "bottom",
  className = "",
  children,
}: DropdownMenuProps) {
  const [open, setOpen] = React.useState(false);
  const ref = React.useRef<HTMLSpanElement>(null);
  const close = React.useCallback(() => setOpen(false), []);

  React.useEffect(() => {
    if (!open) return;
    const onDown = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    };
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    document.addEventListener("mousedown", onDown);
    document.addEventListener("keydown", onKey);
    return () => {
      document.removeEventListener("mousedown", onDown);
      document.removeEventListener("keydown", onKey);
    };
  }, [open]);

  const triggerEl = React.isValidElement(trigger)
    ? React.cloneElement(trigger as React.ReactElement<any>, {
        onClick: (e: React.MouseEvent) => {
          (trigger.props as any).onClick?.(e);
          setOpen((v) => !v);
        },
        "aria-haspopup": "menu",
        "aria-expanded": open,
      })
    : trigger;

  const origin = `${side === "top" ? "bottom" : "top"} ${align === "end" ? "right" : "left"}`;

  return (
    <span className={["jl-menu", className].filter(Boolean).join(" ")} ref={ref}>
      {triggerEl}
      {open && (
        <MenuCtx.Provider value={{ close }}>
          <div
            className="jl-menu__pop"
            role="menu"
            data-side={side}
            data-align={align}
            style={{ "--_origin": origin } as React.CSSProperties}
          >
            {children}
          </div>
        </MenuCtx.Provider>
      )}
    </span>
  );
}

function MenuItem({
  icon = null,
  shortcut = null,
  tone = "default",
  disabled = false,
  onSelect,
  className = "",
  children,
  ...rest
}: DropdownMenuItemProps) {
  const { close } = React.useContext(MenuCtx);
  const cls = [
    "jl-menu__item",
    tone === "danger" ? "jl-menu__item--danger" : "",
    className,
  ]
    .filter(Boolean)
    .join(" ");
  return (
    <button
      type="button"
      role="menuitem"
      className={cls}
      aria-disabled={disabled || undefined}
      onClick={(e) => {
        onSelect?.(e);
        close();
      }}
      {...rest}
    >
      {icon && <span className="jl-menu__item-icon">{icon}</span>}
      <span className="jl-menu__item-label">{children}</span>
      {shortcut && <span className="jl-menu__item-shortcut">{shortcut}</span>}
    </button>
  );
}

function MenuLabel({ className = "", children, ...rest }: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div className={["jl-menu__label", className].filter(Boolean).join(" ")} {...rest}>
      {children}
    </div>
  );
}

function MenuSeparator({ className = "", ...rest }: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div className={["jl-menu__sep", className].filter(Boolean).join(" ")} role="separator" {...rest} />
  );
}

export const DropdownMenu = Object.assign(DropdownMenuRoot, {
  Item: MenuItem,
  Label: MenuLabel,
  Separator: MenuSeparator,
});

// demo/vue/src/components/ui/dropdown-menu/DropdownMenu.vue
<script setup lang="ts">
import { ref, computed, watch, onBeforeUnmount, provide } from "vue";

const props = withDefaults(
  defineProps<{ align?: "start" | "end"; side?: "bottom" | "top" }>(),
  { align: "start", side: "bottom" }
);

const open = ref(false);
const root = ref<HTMLElement | null>(null);
const close = () => (open.value = false);
const toggle = () => (open.value = !open.value);
provide("jlMenu", { close });

function onDown(e: MouseEvent) {
  if (root.value && !root.value.contains(e.target as Node)) close();
}
function onKey(e: KeyboardEvent) {
  if (e.key === "Escape") close();
}
watch(open, (v) => {
  if (v) {
    document.addEventListener("mousedown", onDown);
    document.addEventListener("keydown", onKey);
  } else {
    document.removeEventListener("mousedown", onDown);
    document.removeEventListener("keydown", onKey);
  }
});
onBeforeUnmount(() => {
  document.removeEventListener("mousedown", onDown);
  document.removeEventListener("keydown", onKey);
});

const origin = computed(
  () => `${props.side === "top" ? "bottom" : "top"} ${props.align === "end" ? "right" : "left"}`
);
</script>

<template>
  <span ref="root" class="jl-menu">
    <span :aria-haspopup="'menu'" :aria-expanded="open" @click="toggle">
      <slot name="trigger" />
    </span>
    <div
      v-if="open"
      class="jl-menu__pop"
      role="menu"
      :data-side="side"
      :data-align="align"
      :style="{ '--_origin': origin }"
    >
      <slot />
    </div>
  </span>
</template>

<style src="./dropdown-menu.css"></style>
