// registry/components/tabs/vue/Tabs.vue
<script setup lang="ts">
import { computed } from "vue";

type TabItem =
  | string
  | { value: string; label: string; count?: number; disabled?: boolean };

const props = withDefaults(
  defineProps<{
    items: TabItem[];
    modelValue: string;
    variant?: "line" | "pill";
    orientation?: "horizontal" | "vertical";
  }>(),
  { variant: "line", orientation: "horizontal" }
);

const emit = defineEmits<{
  "update:modelValue": [value: string];
  change: [value: string];
}>();

const vertical = computed(() => props.orientation === "vertical");
const norm = computed(() =>
  props.items.map((it) => (typeof it === "string" ? { value: it, label: it } : it))
);

function select(v: string, disabled?: boolean) {
  if (disabled) return;
  emit("update:modelValue", v);
  emit("change", v);
}
</script>

<template>
  <div
    :class="['jl-tabs', `jl-tabs--${variant}`, vertical ? 'jl-tabs--vertical' : '']"
    role="tablist"
    :aria-orientation="vertical ? 'vertical' : undefined"
  >
    <button
      v-for="t in norm"
      :key="t.value"
      type="button"
      role="tab"
      class="jl-tab"
      :aria-selected="modelValue === t.value"
      :aria-disabled="('disabled' in t && t.disabled) || undefined"
      :disabled="('disabled' in t && t.disabled) || undefined"
      @click="select(t.value, 'disabled' in t ? t.disabled : false)"
    >
      {{ t.label }}
      <span v-if="'count' in t && t.count != null" class="jl-tab__count">{{ t.count }}</span>
    </button>
  </div>
</template>

<style src="./tabs.css"></style>

// registry/components/tabs/react/tabs.tsx
import * as React from "react";
import "./tabs.css";

export type TabItem =
  | string
  | {
      value: string;
      label: React.ReactNode;
      icon?: React.ReactNode;
      count?: number;
      disabled?: boolean;
    };

export interface TabsProps extends Omit<React.HTMLAttributes<HTMLDivElement>, "onChange"> {
  items: TabItem[];
  value: string;
  onChange?: (value: string) => void;
  variant?: "line" | "pill";
  orientation?: "horizontal" | "vertical";
}

export function Tabs({
  items = [],
  value,
  onChange,
  variant = "line",
  orientation = "horizontal",
  className = "",
  ...rest
}: TabsProps) {
  const vertical = orientation === "vertical";
  return (
    <div
      className={[
        "jl-tabs",
        `jl-tabs--${variant}`,
        vertical ? "jl-tabs--vertical" : "",
        className,
      ]
        .filter(Boolean)
        .join(" ")}
      role="tablist"
      aria-orientation={vertical ? "vertical" : undefined}
      {...rest}
    >
      {items.map((it) => {
        const tab = typeof it === "string" ? { value: it, label: it } : it;
        const selected = value === tab.value;
        const disabled = "disabled" in tab && tab.disabled;
        return (
          <button
            key={tab.value}
            type="button"
            role="tab"
            className="jl-tab"
            aria-selected={selected}
            aria-disabled={disabled || undefined}
            disabled={disabled || undefined}
            onClick={() => !disabled && onChange?.(tab.value)}
          >
            {"icon" in tab && tab.icon}
            {tab.label}
            {"count" in tab && tab.count != null && (
              <span className="jl-tab__count">{tab.count}</span>
            )}
          </button>
        );
      })}
    </div>
  );
}
