// demo/react/src/components/ui/switch/switch.tsx
import * as React from "react";
import "./switch.css";

export type SwitchSize = "sm" | "md";

export interface SwitchProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "type" | "size"> {
  label?: React.ReactNode;
  size?: SwitchSize;
}

const Switch = React.forwardRef<HTMLInputElement, SwitchProps>(
  ({ label, size = "md", disabled = false, className = "", ...props }, ref) => {
    return (
      <label
        className={["jl-switch", `jl-switch--${size}`, className].filter(Boolean).join(" ")}
        data-disabled={disabled || undefined}
      >
        <input
          ref={ref}
          type="checkbox"
          role="switch"
          className="jl-switch__input"
          disabled={disabled}
          {...props}
        />
        <span className="jl-switch__track">
          <span className="jl-switch__thumb" />
        </span>
        {label && <span className="jl-switch__label">{label}</span>}
      </label>
    );
  }
);

Switch.displayName = "Switch";

export { Switch };

// registry/components/switch/vue/Switch.vue
<script setup lang="ts">
type SwitchSize = "sm" | "md";

const props = withDefaults(
  defineProps<{
    label?: string;
    size?: SwitchSize;
    disabled?: boolean;
    modelValue?: boolean;
  }>(),
  { label: "", size: "md", disabled: false, modelValue: false }
);

const emit = defineEmits<{
  "update:modelValue": [value: boolean];
}>();

function onChange(event: Event) {
  emit("update:modelValue", (event.target as HTMLInputElement).checked);
}
</script>

<template>
  <label
    class="jl-switch"
    :class="`jl-switch--${props.size}`"
    :data-disabled="props.disabled || undefined"
  >
    <input
      type="checkbox"
      role="switch"
      class="jl-switch__input"
      :checked="props.modelValue"
      :disabled="props.disabled"
      v-bind="$attrs"
      @change="onChange"
    />
    <span class="jl-switch__track"><span class="jl-switch__thumb" /></span>
    <span v-if="props.label || $slots.default" class="jl-switch__label"><slot>{{ props.label }}</slot></span>
  </label>
</template>

<style src="./switch.css"></style>
