// registry/components/tooltip/react/tooltip.tsx
import * as React from "react";
import { useAnchoredPopup, AnchoredPortal } from "../anchored-popup";
import "./tooltip.css";

export type TooltipSide = "top" | "bottom" | "left" | "right";

export interface TooltipProps {
  content: React.ReactNode;
  side?: TooltipSide;
  delay?: number;
  /** Controlled open state. Omit for uncontrolled hover/focus behavior. */
  open?: boolean;
  /** Called when the tooltip wants to open or close. */
  onOpenChange?: (open: boolean) => void;
  /** Render the trigger without any tooltip. @default false */
  disabled?: boolean;
  className?: string;
  children: React.ReactNode;
}

export function Tooltip({
  content,
  side = "top",
  delay = 120,
  open,
  onOpenChange,
  disabled = false,
  className = "",
  children,
}: TooltipProps) {
  const isControlled = open !== undefined;
  const [internal, setInternal] = React.useState(false);
  const show = isControlled ? open : internal;
  const set = (v: boolean) => {
    if (!isControlled) setInternal(v);
    onOpenChange?.(v);
  };
  const timer = React.useRef<ReturnType<typeof setTimeout> | null>(null);

  // The bubble is portaled to <body> so a clipping ancestor (a Card's overflow: hidden,
  // a scrolling table wrapper) can't crop it, and anchored to the trigger instead. It
  // stays mounted — `retainOnClose` keeps the last position so the fade-out plays in
  // place rather than jumping. Tooltips are suppressed on touch, so no sheet.
  const { anchorRef, popupRef } = useAnchoredPopup<HTMLSpanElement, HTMLSpanElement>({
    open: show,
    side,
    align: "center",
    gap: 8,
    sheetBreakpoint: 0,
    retainOnClose: true,
  });

  const openIt = () => {
    timer.current = setTimeout(() => set(true), delay);
  };
  const close = () => {
    if (timer.current) clearTimeout(timer.current);
    set(false);
  };

  if (disabled || content == null) return <>{children}</>;

  return (
    <span
      ref={anchorRef}
      className={["jl-tooltip", className].filter(Boolean).join(" ")}
      onMouseEnter={openIt}
      onMouseLeave={close}
      onFocus={openIt}
      onBlur={close}
    >
      {children}
      <AnchoredPortal>
        <span
          ref={popupRef}
          className="jl-tooltip__pop"
          role="tooltip"
          data-side={side}
          data-show={show || undefined}
        >
          {content}
          <span className="jl-tooltip__arrow" />
        </span>
      </AnchoredPortal>
    </span>
  );
}

// registry/components/tooltip/vue/Tooltip.vue
<script setup lang="ts">
import { ref, computed, onBeforeUnmount } from "vue";
import { useAnchoredPopup } from "../anchored-popup";

type TooltipSide = "top" | "bottom" | "left" | "right";

const props = withDefaults(
  defineProps<{
    content?: string;
    side?: TooltipSide;
    delay?: number;
    /** Controlled open state (`v-model:open`). Omit for uncontrolled hover/focus. */
    open?: boolean;
    /** Render the trigger without any tooltip. @default false */
    disabled?: boolean;
  }>(),
  { content: "", side: "top", delay: 120, disabled: false, open: undefined }
);

const emit = defineEmits<{ "update:open": [value: boolean] }>();

const isControlled = computed(() => props.open !== undefined);
const internal = ref(false);
const show = computed(() => !!(isControlled.value ? props.open : internal.value));

// The bubble is teleported to <body> so a clipping ancestor (a Card's overflow: hidden,
// a scrolling table wrapper) can't crop it, and anchored to the trigger instead. It stays
// mounted — `retainOnClose` keeps the last position so the fade-out plays in place rather
// than jumping. Tooltips are suppressed on touch, so no sheet.
const { anchorRef, popupRef } = useAnchoredPopup({
  open: show,
  side: props.side,
  align: "center",
  gap: 8,
  sheetBreakpoint: 0,
  retainOnClose: true,
});

let timer: ReturnType<typeof setTimeout> | null = null;
function set(v: boolean) {
  if (!isControlled.value) internal.value = v;
  emit("update:open", v);
}
function onEnter() {
  timer = setTimeout(() => set(true), props.delay);
}
function close() {
  if (timer) clearTimeout(timer);
  set(false);
}
onBeforeUnmount(() => timer && clearTimeout(timer));
</script>

<template>
  <span v-if="disabled" class="jl-tooltip">
    <slot />
  </span>
  <span
    v-else
    ref="anchorRef"
    class="jl-tooltip"
    @mouseenter="onEnter"
    @mouseleave="close"
    @focusin="onEnter"
    @focusout="close"
  >
    <slot />
    <Teleport to="body">
      <span
        ref="popupRef"
        class="jl-tooltip__pop"
        role="tooltip"
        :data-side="side"
        :data-show="show || undefined"
      >
        <slot name="content">{{ content }}</slot>
        <span class="jl-tooltip__arrow" />
      </span>
    </Teleport>
  </span>
</template>

<style src="./tooltip.css"></style>
