// demo/vue/src/components/ui/button/Button.vue
<script setup lang="ts">
type ButtonVariant = "primary" | "secondary" | "ghost" | "subtle" | "danger";
type ButtonSize = "sm" | "md" | "lg";

const props = withDefaults(
  defineProps<{
    variant?: ButtonVariant;
    size?: ButtonSize;
    fullWidth?: boolean;
    disabled?: boolean;
    type?: "button" | "submit" | "reset";
  }>(),
  {
    variant: "primary",
    size: "md",
    fullWidth: false,
    disabled: false,
    type: "button",
  }
);

const cls = [
  "jl-btn",
  `jl-btn--${props.variant}`,
  `jl-btn--${props.size}`,
  props.fullWidth ? "jl-btn--block" : "",
]
  .filter(Boolean)
  .join(" ");
</script>

<template>
  <button :type="props.type" :disabled="props.disabled" :class="cls">
    <slot name="icon" />
    <span v-if="$slots.default"><slot /></span>
    <slot name="trailing-icon" />
  </button>
</template>

<style src="./button.css"></style>

// registry/components/button/react/button.tsx
import * as React from "react";
import "./button.css";

export type ButtonVariant = "primary" | "secondary" | "ghost" | "subtle" | "danger";
export type ButtonSize = "sm" | "md" | "lg";

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?: ButtonSize;
  icon?: React.ReactNode;
  trailingIcon?: React.ReactNode;
  fullWidth?: boolean;
  as?: "button" | "a";
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      variant = "primary",
      size = "md",
      icon,
      trailingIcon,
      fullWidth = false,
      as: Tag = "button",
      className = "",
      children,
      ...props
    },
    ref
  ) => {
    const cls = [
      "jl-btn",
      `jl-btn--${variant}`,
      `jl-btn--${size}`,
      fullWidth ? "jl-btn--block" : "",
      className,
    ]
      .filter(Boolean)
      .join(" ");

    const Component = Tag as React.ElementType;
    return (
      <Component ref={ref} className={cls} {...props}>
        {icon}
        {children != null && <span>{children}</span>}
        {trailingIcon}
      </Component>
    );
  }
);

Button.displayName = "Button";

export { Button };
