// registry/components/app-shell/vue/AppShell.vue
<script setup lang="ts">
import { ref, computed, provide, onMounted, onBeforeUnmount, watch, type CSSProperties, type Ref } from "vue";

export interface AppShellCtx {
  open: Ref<boolean>;
  setOpen: (open: boolean) => void;
}

const props = withDefaults(
  defineProps<{
    padded?: boolean;
    fullHeight?: boolean;
    mobileBreakpoint?: number;
    mobileOpen?: boolean;
    defaultMobileOpen?: boolean;
  }>(),
  {
    padded: false,
    fullHeight: true,
    mobileBreakpoint: 880,
    mobileOpen: undefined,
    defaultMobileOpen: false,
  }
);

const emit = defineEmits<{ (e: "update:mobileOpen", value: boolean): void }>();

const mobile = ref(false);
const internalOpen = ref(props.defaultMobileOpen);
const isControlled = computed(() => props.mobileOpen != null);
const open = computed(() => (isControlled.value ? props.mobileOpen! : internalOpen.value));

function setOpen(next: boolean) {
  if (!isControlled.value) internalOpen.value = next;
  emit("update:mobileOpen", next);
}

let mql: MediaQueryList | null = null;
function apply() {
  if (mql) mobile.value = mql.matches;
}

onMounted(() => {
  if (typeof window === "undefined" || !window.matchMedia) return;
  mql = window.matchMedia(`(max-width: ${props.mobileBreakpoint}px)`);
  apply();
  mql.addEventListener("change", apply);
});
onBeforeUnmount(() => {
  if (mql) mql.removeEventListener("change", apply);
});

// Close the drawer when leaving mobile.
watch(mobile, (m) => {
  if (!m && open.value) setOpen(false);
});

provide<AppShellCtx>("jlAppShell", { open, setOpen });

const rootStyle = computed<CSSProperties>(() => ({
  height: props.fullHeight ? "100dvh" : "100%",
}));
</script>

<template>
  <div
    class="jl-appshell"
    :data-mobile="mobile || undefined"
    :data-open="mobile && open ? 'true' : undefined"
    :style="rootStyle"
  >
    <div v-if="$slots.sidebar" class="jl-appshell__aside"><slot name="sidebar" /></div>
    <div v-if="mobile" class="jl-appshell__backdrop" aria-hidden="true" @click="setOpen(false)" />
    <div class="jl-appshell__main">
      <div v-if="$slots.header" class="jl-appshell__header"><slot name="header" /></div>
      <div :class="['jl-appshell__content', padded ? 'jl-appshell__content--padded' : '']">
        <slot />
      </div>
    </div>
  </div>
</template>

<style src="./app-shell.css"></style>

// registry/components/app-shell/react/app-shell.tsx
/* eslint-disable react-refresh/only-export-components */
import * as React from "react";
import "./app-shell.css";

export interface AppShellProps extends React.HTMLAttributes<HTMLDivElement> {
  sidebar?: React.ReactNode;
  header?: React.ReactNode;
  padded?: boolean;
  fullHeight?: boolean;
  mobileBreakpoint?: number;
  mobileOpen?: boolean;
  defaultMobileOpen?: boolean;
  onMobileOpenChange?: (open: boolean) => void;
}

export type AppShellMenuButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement>;

interface AppShellComposition {
  (props: AppShellProps): React.JSX.Element;
  MenuButton: (props: AppShellMenuButtonProps) => React.JSX.Element;
}

const ShellCtx = React.createContext<{
  mobile: boolean;
  open: boolean;
  setOpen: (open: boolean) => void;
}>({ mobile: false, open: false, setOpen: () => {} });

function MenuButton({ className = "", children, ...rest }: AppShellMenuButtonProps) {
  const { open, setOpen } = React.useContext(ShellCtx);
  return (
    <button
      type="button"
      className={["jl-appshell__menubtn", className].filter(Boolean).join(" ")}
      aria-label={open ? "Close navigation" : "Open navigation"}
      aria-expanded={open}
      onClick={() => setOpen(!open)}
      {...rest}
    >
      {children || (
        <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
          <path d="M4 7h16M4 12h16M4 17h16" stroke="currentColor" strokeWidth="1.85" strokeLinecap="round" />
        </svg>
      )}
    </button>
  );
}

function AppShellRoot({
  sidebar,
  header,
  padded = false,
  fullHeight = true,
  mobileBreakpoint = 880,
  mobileOpen: openProp,
  defaultMobileOpen = false,
  onMobileOpenChange,
  className = "",
  style,
  children,
  ...rest
}: AppShellProps) {
  const [mobile, setMobile] = React.useState(false);
  const isControlled = openProp != null;
  const [internalOpen, setInternalOpen] = React.useState(defaultMobileOpen);
  const open = isControlled ? openProp : internalOpen;

  const setOpen = React.useCallback(
    (next: boolean) => {
      if (!isControlled) setInternalOpen(next);
      onMobileOpenChange?.(next);
    },
    [isControlled, onMobileOpenChange]
  );

  React.useEffect(() => {
    if (typeof window === "undefined" || !window.matchMedia) return;
    const mql = window.matchMedia(`(max-width: ${mobileBreakpoint}px)`);
    // Sync mobile mode and close the drawer whenever we leave mobile.
    const apply = () => {
      setMobile(mql.matches);
      if (!mql.matches) setOpen(false);
    };
    apply();
    mql.addEventListener("change", apply);
    return () => mql.removeEventListener("change", apply);
  }, [mobileBreakpoint, setOpen]);

  const ctx = React.useMemo(() => ({ mobile, open, setOpen }), [mobile, open, setOpen]);

  return (
    <ShellCtx.Provider value={ctx}>
      <div
        className={["jl-appshell", className].filter(Boolean).join(" ")}
        data-mobile={mobile || undefined}
        data-open={mobile && open ? "true" : undefined}
        style={{ height: fullHeight ? "100dvh" : "100%", ...style }}
        {...rest}
      >
        {sidebar != null && <div className="jl-appshell__aside">{sidebar}</div>}
        {mobile && (
          <div className="jl-appshell__backdrop" onClick={() => setOpen(false)} aria-hidden="true" />
        )}
        <div className="jl-appshell__main">
          {header != null && <div className="jl-appshell__header">{header}</div>}
          <div
            className={["jl-appshell__content", padded ? "jl-appshell__content--padded" : ""]
              .filter(Boolean)
              .join(" ")}
          >
            {children}
          </div>
        </div>
      </div>
    </ShellCtx.Provider>
  );
}

export const AppShell = Object.assign(AppShellRoot, {
  MenuButton,
}) as AppShellComposition;
