// registry/components/skeleton/react/skeleton.tsx
import * as React from "react";
import "./skeleton.css";

export type SkeletonVariant = "text" | "circle" | "rect";

export interface SkeletonProps extends React.HTMLAttributes<HTMLSpanElement> {
  variant?: SkeletonVariant;
  width?: number | string;
  height?: number | string;
  lines?: number;
  radius?: number | string;
}

const dim = (v?: number | string) => (typeof v === "number" ? `${v}px` : v);

const Skeleton = React.forwardRef<HTMLSpanElement, SkeletonProps>(
  (
    {
      variant = "text",
      width,
      height,
      lines = 1,
      radius,
      className = "",
      style,
      ...props
    },
    ref
  ) => {
    if (variant === "text" && lines > 1) {
      return (
        <div
          className={["jl-skel-lines", className].filter(Boolean).join(" ")}
          aria-hidden="true"
          {...(props as React.HTMLAttributes<HTMLDivElement>)}
        >
          {Array.from({ length: lines }).map((_, i) => (
            <span
              key={i}
              className="jl-skel jl-skel--text"
              style={{ width: i === lines - 1 ? "62%" : width ? dim(width) : "100%" }}
            />
          ))}
        </div>
      );
    }

    const isCircle = variant === "circle";
    const resolved: React.CSSProperties = {
      width: dim(width ?? (isCircle ? 40 : undefined)),
      height: dim(height ?? (isCircle ? width ?? 40 : undefined)),
      borderRadius: radius != null ? dim(radius) : undefined,
      ...style,
    };

    return (
      <span
        ref={ref}
        className={["jl-skel", `jl-skel--${variant}`, className]
          .filter(Boolean)
          .join(" ")}
        style={resolved}
        aria-hidden="true"
        {...props}
      />
    );
  }
);

Skeleton.displayName = "Skeleton";

export { Skeleton };

// registry/components/skeleton/vue/Skeleton.vue
<script setup lang="ts">
import { computed } from "vue";

type SkeletonVariant = "text" | "circle" | "rect";

const props = withDefaults(
  defineProps<{
    variant?: SkeletonVariant;
    width?: number | string;
    height?: number | string;
    lines?: number;
    radius?: number | string;
  }>(),
  { variant: "text", width: undefined, height: undefined, lines: 1, radius: undefined }
);

const dim = (v?: number | string) => (typeof v === "number" ? `${v}px` : v);

const isMultiline = computed(() => props.variant === "text" && props.lines > 1);

const resolved = computed(() => {
  const isCircle = props.variant === "circle";
  return {
    width: dim(props.width ?? (isCircle ? 40 : undefined)),
    height: dim(props.height ?? (isCircle ? props.width ?? 40 : undefined)),
    borderRadius: props.radius != null ? dim(props.radius) : undefined,
  };
});
</script>

<template>
  <div v-if="isMultiline" class="jl-skel-lines" aria-hidden="true">
    <span
      v-for="i in props.lines"
      :key="i"
      class="jl-skel jl-skel--text"
      :style="{ width: i === props.lines ? '62%' : (props.width ? dim(props.width) : '100%') }"
    />
  </div>
  <span
    v-else
    class="jl-skel"
    :class="`jl-skel--${props.variant}`"
    :style="resolved"
    aria-hidden="true"
  />
</template>

<style src="./skeleton.css"></style>
