// demo/react/src/components/ui/kbd/kbd.tsx
import * as React from "react";
import "./kbd.css";

export type KbdSize = "sm" | "md";

export interface KbdProps extends React.HTMLAttributes<HTMLElement> {
  keys?: string[];
  size?: KbdSize;
}

const PRETTY: Record<string, string> = {
  mod: "⌘", cmd: "⌘", meta: "⌘", shift: "⇧", alt: "⌥", option: "⌥",
  ctrl: "⌃", control: "⌃", enter: "↵", return: "↵", esc: "Esc",
  escape: "Esc", tab: "Tab", up: "↑", down: "↓", left: "←", right: "→",
  backspace: "⌫", del: "⌦", delete: "⌦", space: "Space",
};

function prettify(k: React.ReactNode): React.ReactNode {
  if (typeof k !== "string") return k;
  return PRETTY[k.toLowerCase()] ?? (k.length === 1 ? k.toUpperCase() : k);
}

const Kbd = React.forwardRef<HTMLElement, KbdProps>(
  ({ keys, size = "md", className = "", children, ...props }, ref) => {
    const cls = ["jl-kbd", size === "sm" ? "jl-kbd--sm" : "", className]
      .filter(Boolean)
      .join(" ");

    if (keys && keys.length) {
      return (
        <span className="jl-kbd-group" {...props}>
          {keys.map((k, i) => (
            <React.Fragment key={i}>
              {i > 0 && (
                <span className="jl-kbd-group__plus" aria-hidden="true">
                  +
                </span>
              )}
              <kbd className={cls}>{prettify(k)}</kbd>
            </React.Fragment>
          ))}
        </span>
      );
    }

    return (
      <kbd ref={ref} className={cls} {...props}>
        {prettify(children)}
      </kbd>
    );
  }
);

Kbd.displayName = "Kbd";

export { Kbd };

// registry/components/kbd/vue/Kbd.vue
<script setup lang="ts">
import { computed } from "vue";

type KbdSize = "sm" | "md";

const props = withDefaults(
  defineProps<{
    keys?: string[];
    size?: KbdSize;
  }>(),
  { size: "md" }
);

const PRETTY: Record<string, string> = {
  mod: "⌘", cmd: "⌘", meta: "⌘", shift: "⇧", alt: "⌥", option: "⌥",
  ctrl: "⌃", control: "⌃", enter: "↵", return: "↵", esc: "Esc",
  escape: "Esc", tab: "Tab", up: "↑", down: "↓", left: "←", right: "→",
  backspace: "⌫", del: "⌦", delete: "⌦", space: "Space",
};

function prettify(k: string): string {
  return PRETTY[k.toLowerCase()] ?? (k.length === 1 ? k.toUpperCase() : k);
}

const cls = computed(() =>
  ["jl-kbd", props.size === "sm" ? "jl-kbd--sm" : ""].filter(Boolean).join(" ")
);
</script>

<template>
  <span v-if="props.keys && props.keys.length" class="jl-kbd-group">
    <template v-for="(k, i) in props.keys" :key="i">
      <span v-if="i > 0" class="jl-kbd-group__plus" aria-hidden="true">+</span>
      <kbd :class="cls">{{ prettify(k) }}</kbd>
    </template>
  </span>
  <kbd v-else :class="cls"><slot /></kbd>
</template>

<style src="./kbd.css"></style>
