// demo/react/src/components/ui/popover/popover.tsx
import * as React from "react";
import "./popover.css";

export type PopoverSide = "bottom" | "top";
export type PopoverAlign = "start" | "center" | "end";

interface TriggerProps {
  onClick?: (e: React.MouseEvent) => void;
  "aria-haspopup"?: React.AriaAttributes["aria-haspopup"];
  "aria-expanded"?: boolean;
}

export interface PopoverProps {
  trigger: React.ReactElement;
  side?: PopoverSide;
  align?: PopoverAlign;
  arrow?: boolean;
  padded?: boolean;
  defaultOpen?: boolean;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  className?: string;
  children?: React.ReactNode | ((api: { close: () => void }) => React.ReactNode);
}

export function Popover({
  trigger,
  side = "bottom",
  align = "center",
  arrow = true,
  padded = true,
  defaultOpen = false,
  open: controlledOpen,
  onOpenChange,
  className = "",
  children,
}: PopoverProps) {
  const isControlled = controlledOpen != null;
  const [uncontrolled, setUncontrolled] = React.useState(defaultOpen);
  const open = isControlled ? controlledOpen : uncontrolled;
  const ref = React.useRef<HTMLSpanElement>(null);

  const setOpen = React.useCallback(
    (v: boolean) => {
      if (!isControlled) setUncontrolled(v);
      if (onOpenChange) onOpenChange(v);
    },
    [isControlled, onOpenChange]
  );

  React.useEffect(() => {
    if (!open) return;
    const onDown = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    };
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    document.addEventListener("mousedown", onDown);
    document.addEventListener("keydown", onKey);
    return () => {
      document.removeEventListener("mousedown", onDown);
      document.removeEventListener("keydown", onKey);
    };
  }, [open, setOpen]);

  const triggerEl = React.isValidElement(trigger)
    ? React.cloneElement(trigger as React.ReactElement<TriggerProps>, {
        onClick: (e: React.MouseEvent) => {
          (trigger.props as TriggerProps).onClick?.(e);
          setOpen(!open);
        },
        "aria-haspopup": "dialog",
        "aria-expanded": open,
      })
    : trigger;

  const origin = `${side === "top" ? "bottom" : "top"} ${align}`;

  return (
    <span className={["jl-popover", className].filter(Boolean).join(" ")} ref={ref}>
      {triggerEl}
      {open && (
        <div
          className="jl-popover__pop"
          role="dialog"
          data-side={side}
          data-align={align}
          style={
            {
              "--_origin": origin,
              "--_pad": padded ? undefined : "0",
            } as React.CSSProperties
          }
        >
          {arrow && <span className="jl-popover__arrow" aria-hidden="true" />}
          {typeof children === "function"
            ? children({ close: () => setOpen(false) })
            : children}
        </div>
      )}
    </span>
  );
}

// registry/components/popover/vue/Popover.vue
<script setup lang="ts">
import { ref, computed, watch, onBeforeUnmount } from "vue";

type Side = "bottom" | "top";
type Align = "start" | "center" | "end";

const props = withDefaults(
  defineProps<{
    side?: Side;
    align?: Align;
    arrow?: boolean;
    padded?: boolean;
    defaultOpen?: boolean;
    open?: boolean;
  }>(),
  { side: "bottom", align: "center", arrow: true, padded: true, defaultOpen: false, open: undefined }
);

const emit = defineEmits<{ (e: "update:open", v: boolean): void }>();

const isControlled = computed(() => props.open !== undefined);
const internal = ref(props.defaultOpen);
const open = computed(() => (isControlled.value ? props.open! : internal.value));
const root = ref<HTMLElement | null>(null);

function setOpen(v: boolean) {
  if (!isControlled.value) internal.value = v;
  emit("update:open", v);
}
const toggle = () => setOpen(!open.value);
const close = () => setOpen(false);

function onDown(e: MouseEvent) {
  if (root.value && !root.value.contains(e.target as Node)) close();
}
function onKey(e: KeyboardEvent) {
  if (e.key === "Escape") close();
}
watch(open, (v) => {
  if (v) {
    document.addEventListener("mousedown", onDown);
    document.addEventListener("keydown", onKey);
  } else {
    document.removeEventListener("mousedown", onDown);
    document.removeEventListener("keydown", onKey);
  }
});
onBeforeUnmount(() => {
  document.removeEventListener("mousedown", onDown);
  document.removeEventListener("keydown", onKey);
});

const origin = computed(() => `${props.side === "top" ? "bottom" : "top"} ${props.align}`);
const popStyle = computed(() => ({
  "--_origin": origin.value,
  "--_pad": props.padded ? undefined : "0",
}));
</script>

<template>
  <span ref="root" class="jl-popover">
    <span class="jl-popover__trigger" :aria-haspopup="'dialog'" :aria-expanded="open" @click="toggle">
      <slot name="trigger" />
    </span>
    <div
      v-if="open"
      class="jl-popover__pop"
      role="dialog"
      :data-side="side"
      :data-align="align"
      :style="popStyle"
    >
      <span v-if="arrow" class="jl-popover__arrow" aria-hidden="true" />
      <slot :close="close" />
    </div>
  </span>
</template>

<style src="./popover.css"></style>
