// demo/vue/src/components/ui/tag/Tag.vue
<script setup lang="ts">
import { computed, useAttrs } from "vue";

const props = withDefaults(
  defineProps<{
    selected?: boolean;
    /** When true, renders an × button that emits `remove`. */
    removable?: boolean;
  }>(),
  { selected: false, removable: false }
);

const emit = defineEmits<{
  remove: [event: MouseEvent];
}>();

const attrs = useAttrs();

const interactive = computed(() => "onClick" in attrs);

const cls = computed(() =>
  [
    "jl-tag",
    interactive.value ? "jl-tag--button" : "",
    props.selected ? "jl-tag--selected" : "",
  ]
    .filter(Boolean)
    .join(" ")
);

function onRemove(event: MouseEvent) {
  event.stopPropagation();
  emit("remove", event);
}
</script>

<template>
  <span :class="cls">
    <slot name="icon" />
    <slot />
    <button
      v-if="props.removable"
      type="button"
      class="jl-tag__remove"
      aria-label="Remove"
      @click="onRemove"
    >
      <svg viewBox="0 0 12 12" width="12" height="12" fill="none" aria-hidden="true">
        <path d="M3 3l6 6M9 3l-6 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
      </svg>
    </button>
  </span>
</template>

<style src="./tag.css"></style>

// registry/components/tag/react/tag.tsx
import * as React from "react";
import "./tag.css";

export interface TagProps extends React.HTMLAttributes<HTMLSpanElement> {
  selected?: boolean;
  /** If provided, renders an × button; called when clicked. */
  onRemove?: (e: React.MouseEvent) => void;
  icon?: React.ReactNode;
}

const Tag = React.forwardRef<HTMLSpanElement, TagProps>(
  ({ selected = false, onRemove, icon, onClick, className = "", children, ...props }, ref) => {
    const interactive = !!onClick;
    const cls = [
      "jl-tag",
      interactive ? "jl-tag--button" : "",
      selected ? "jl-tag--selected" : "",
      className,
    ]
      .filter(Boolean)
      .join(" ");

    return (
      <span ref={ref} className={cls} onClick={onClick} {...props}>
        {icon}
        {children}
        {onRemove && (
          <button
            type="button"
            className="jl-tag__remove"
            aria-label="Remove"
            onClick={(e) => {
              e.stopPropagation();
              onRemove(e);
            }}
          >
            <svg viewBox="0 0 12 12" width="12" height="12" fill="none" aria-hidden="true">
              <path d="M3 3l6 6M9 3l-6 6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
            </svg>
          </button>
        )}
      </span>
    );
  }
);

Tag.displayName = "Tag";

export { Tag };
