// registry/components/checkbox/react/checkbox.tsx
import * as React from "react";
import "./checkbox.css";

export interface CheckboxProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "type"> {
  label?: React.ReactNode;
  description?: React.ReactNode;
  indeterminate?: boolean;
  /** Error styling on the box. @default false */
  invalid?: boolean;
}

const Checkbox = React.forwardRef<HTMLInputElement, CheckboxProps>(
  (
    { label, description, indeterminate = false, disabled = false, invalid = false, className = "", ...props },
    ref
  ) => {
    const innerRef = React.useRef<HTMLInputElement>(null);
    React.useImperativeHandle(ref, () => innerRef.current as HTMLInputElement);
    React.useEffect(() => {
      if (innerRef.current) innerRef.current.indeterminate = indeterminate;
    }, [indeterminate]);

    return (
      <label
        className={["jl-check", className].filter(Boolean).join(" ")}
        data-disabled={disabled || undefined}
        data-invalid={invalid || undefined}
      >
        <input
          ref={innerRef}
          type="checkbox"
          className="jl-check__input"
          disabled={disabled}
          aria-invalid={invalid || undefined}
          {...props}
        />
        <span className="jl-check__box">
          <svg className="jl-check__mark" viewBox="0 0 12 12" fill="none" aria-hidden="true">
            <path
              d="M2.5 6.2l2.2 2.3 4.8-5"
              stroke="currentColor"
              strokeWidth="1.8"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
          <span className="jl-check__dash" aria-hidden="true" />
        </span>
        {(label || description) && (
          <span className="jl-check__body">
            {label && <span className="jl-check__label">{label}</span>}
            {description && <span className="jl-check__desc">{description}</span>}
          </span>
        )}
      </label>
    );
  }
);

Checkbox.displayName = "Checkbox";

export { Checkbox };

// registry/components/checkbox/vue/Checkbox.vue
<script setup lang="ts">
import { ref, watch, onMounted } from "vue";

const props = withDefaults(
  defineProps<{
    label?: string;
    description?: string;
    indeterminate?: boolean;
    disabled?: boolean;
    /** Error styling on the box. @default false */
    invalid?: boolean;
    modelValue?: boolean;
  }>(),
  { label: "", description: "", indeterminate: false, disabled: false, invalid: false, modelValue: false }
);

const emit = defineEmits<{
  (e: "update:modelValue", value: boolean): void;
}>();

const input = ref<HTMLInputElement | null>(null);

function syncIndeterminate() {
  if (input.value) input.value.indeterminate = props.indeterminate;
}
onMounted(syncIndeterminate);
watch(() => props.indeterminate, syncIndeterminate);

function onChange(event: Event) {
  emit("update:modelValue", (event.target as HTMLInputElement).checked);
}
</script>

<template>
  <label
    class="jl-check"
    :data-disabled="props.disabled || undefined"
    :data-invalid="props.invalid || undefined"
  >
    <input
      ref="input"
      type="checkbox"
      class="jl-check__input"
      :checked="props.modelValue"
      :disabled="props.disabled"
      :aria-invalid="props.invalid || undefined"
      v-bind="$attrs"
      @change="onChange"
    />
    <span class="jl-check__box">
      <svg class="jl-check__mark" viewBox="0 0 12 12" fill="none" aria-hidden="true">
        <path d="M2.5 6.2l2.2 2.3 4.8-5" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" />
      </svg>
      <span class="jl-check__dash" aria-hidden="true" />
    </span>
    <span v-if="props.label || props.description || $slots.default" class="jl-check__body">
      <span v-if="props.label || $slots.default" class="jl-check__label"><slot>{{ props.label }}</slot></span>
      <span v-if="props.description" class="jl-check__desc">{{ props.description }}</span>
    </span>
  </label>
</template>

<style src="./checkbox.css"></style>
