// demo/vue/src/components/ui/tooltip/Tooltip.vue
<script setup lang="ts">
import { ref, onBeforeUnmount } from "vue";

type TooltipSide = "top" | "bottom" | "left" | "right";

const props = withDefaults(
  defineProps<{ content?: string; side?: TooltipSide; delay?: number }>(),
  { content: "", side: "top", delay: 120 }
);

const show = ref(false);
let timer: ReturnType<typeof setTimeout> | null = null;

function open() {
  timer = setTimeout(() => (show.value = true), props.delay);
}
function close() {
  if (timer) clearTimeout(timer);
  show.value = false;
}
onBeforeUnmount(() => timer && clearTimeout(timer));
</script>

<template>
  <span class="jl-tooltip" @mouseenter="open" @mouseleave="close" @focusin="open" @focusout="close">
    <slot />
    <span class="jl-tooltip__pop" role="tooltip" :data-side="side" :data-show="show || undefined">
      <slot name="content">{{ content }}</slot>
      <span class="jl-tooltip__arrow" />
    </span>
  </span>
</template>

<style src="./tooltip.css"></style>

// registry/components/tooltip/react/tooltip.tsx
import * as React from "react";
import "./tooltip.css";

export type TooltipSide = "top" | "bottom" | "left" | "right";

export interface TooltipProps {
  content: React.ReactNode;
  side?: TooltipSide;
  delay?: number;
  className?: string;
  children: React.ReactNode;
}

export function Tooltip({
  content,
  side = "top",
  delay = 120,
  className = "",
  children,
}: TooltipProps) {
  const [show, setShow] = React.useState(false);
  const timer = React.useRef<ReturnType<typeof setTimeout> | null>(null);

  const open = () => {
    timer.current = setTimeout(() => setShow(true), delay);
  };
  const close = () => {
    if (timer.current) clearTimeout(timer.current);
    setShow(false);
  };

  return (
    <span
      className={["jl-tooltip", className].filter(Boolean).join(" ")}
      onMouseEnter={open}
      onMouseLeave={close}
      onFocus={open}
      onBlur={close}
    >
      {children}
      <span
        className="jl-tooltip__pop"
        role="tooltip"
        data-side={side}
        data-show={show || undefined}
      >
        {content}
        <span className="jl-tooltip__arrow" />
      </span>
    </span>
  );
}
