// demo/react/src/components/ui/segmented-control/segmented-control.tsx
import * as React from "react";
import "./segmented-control.css";

export interface SegmentedOption {
  value: string;
  label?: React.ReactNode;
  icon?: React.ReactNode;
  disabled?: boolean;
}

export interface SegmentedControlProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, "onChange"> {
  options: (SegmentedOption | string)[];
  value?: string;
  defaultValue?: string;
  size?: "sm" | "md";
  fullWidth?: boolean;
  onChange?: (value: string) => void;
  "aria-label"?: string;
}

export function SegmentedControl({
  options,
  value,
  defaultValue,
  size = "md",
  fullWidth = false,
  onChange,
  className = "",
  "aria-label": ariaLabel,
  ...rest
}: SegmentedControlProps) {
  const norm = options.map((o) =>
    typeof o === "string" ? { value: o, label: o } : o
  );
  const isControlled = value != null;
  const [internal, setInternal] = React.useState(
    defaultValue ?? norm[0]?.value
  );
  const current = isControlled ? value : internal;
  const idx = Math.max(0, norm.findIndex((o) => o.value === current));

  const ref = React.useRef<HTMLDivElement>(null);
  const [thumb, setThumb] = React.useState<{ left: number; width: number } | null>(null);

  React.useLayoutEffect(() => {
    const root = ref.current;
    if (!root) return;
    const btn = root.querySelectorAll<HTMLElement>(".jl-segmented__option")[idx];
    if (btn) {
      const pad = parseFloat(getComputedStyle(root).paddingLeft) || 0;
      setThumb({ left: btn.offsetLeft - pad, width: btn.offsetWidth });
    }
  }, [idx, fullWidth, size, options.length]);

  const select = (v: string, disabled?: boolean) => {
    if (disabled || v === current) return;
    if (!isControlled) setInternal(v);
    onChange?.(v);
  };

  const cls = [
    "jl-segmented",
    size === "sm" ? "jl-segmented--sm" : "",
    fullWidth ? "jl-segmented--full" : "",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <div className={cls} role="radiogroup" aria-label={ariaLabel} ref={ref} {...rest}>
      {thumb && (
        <span
          className="jl-segmented__thumb"
          style={{ transform: `translateX(${thumb.left}px)`, width: thumb.width }}
          aria-hidden="true"
        />
      )}
      {norm.map((o) => (
        <button
          key={o.value}
          type="button"
          role="radio"
          aria-checked={o.value === current}
          disabled={o.disabled}
          className="jl-segmented__option"
          onClick={() => select(o.value, o.disabled)}
        >
          {o.icon}
          {o.label ?? o.value}
        </button>
      ))}
    </div>
  );
}

// registry/components/segmented-control/vue/SegmentedControl.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, nextTick } from "vue";

interface SegmentedOption {
  value: string;
  label?: string;
  disabled?: boolean;
}

const props = withDefaults(
  defineProps<{
    options: (SegmentedOption | string)[];
    modelValue?: string;
    size?: "sm" | "md";
    fullWidth?: boolean;
  }>(),
  { size: "md", fullWidth: false }
);

const emit = defineEmits<{
  (e: "update:modelValue", v: string): void;
  (e: "change", v: string): void;
}>();

const norm = computed(() =>
  props.options.map((o) => (typeof o === "string" ? { value: o, label: o } : o))
);
const current = computed(() => props.modelValue ?? norm.value[0]?.value);

const root = ref<HTMLElement | null>(null);
const thumb = ref<{ left: number; width: number } | null>(null);

function measure() {
  const r = root.value;
  if (!r) return;
  const idx = Math.max(0, norm.value.findIndex((o) => o.value === current.value));
  const btn = r.querySelectorAll<HTMLElement>(".jl-segmented__option")[idx];
  if (btn) {
    const pad = parseFloat(getComputedStyle(r).paddingLeft) || 0;
    thumb.value = { left: btn.offsetLeft - pad, width: btn.offsetWidth };
  }
}

onMounted(() => {
  nextTick(measure);
  if (typeof document !== "undefined" && document.fonts?.ready) {
    document.fonts.ready.then(measure);
  }
});
watch(
  [current, () => props.fullWidth, () => props.size, () => props.options.length],
  () => nextTick(measure)
);

function select(o: SegmentedOption) {
  if (o.disabled || o.value === current.value) return;
  emit("update:modelValue", o.value);
  emit("change", o.value);
}

const cls = computed(() =>
  [
    "jl-segmented",
    props.size === "sm" ? "jl-segmented--sm" : "",
    props.fullWidth ? "jl-segmented--full" : "",
  ]
    .filter(Boolean)
    .join(" ")
);
</script>

<template>
  <div ref="root" :class="cls" role="radiogroup">
    <span
      v-if="thumb"
      class="jl-segmented__thumb"
      :style="{ transform: `translateX(${thumb.left}px)`, width: thumb.width + 'px' }"
      aria-hidden="true"
    />
    <button
      v-for="o in norm"
      :key="o.value"
      type="button"
      role="radio"
      :aria-checked="o.value === current"
      :disabled="o.disabled"
      class="jl-segmented__option"
      @click="select(o)"
    >
      {{ o.label ?? o.value }}
    </button>
  </div>
</template>

<style src="./segmented-control.css"></style>
