// registry/components/slider/vue/Slider.vue
<script setup lang="ts">
import { ref, computed } from "vue";

type SliderMark = number | { value: number; label: string };
type SliderSize = "sm" | "md" | "lg";
type SliderValue = number | [number, number];

const props = withDefaults(
  defineProps<{
    min?: number;
    max?: number;
    step?: number;
    modelValue?: SliderValue;
    range?: boolean;
    disabled?: boolean;
    size?: SliderSize;
    marks?: SliderMark[];
    showValue?: boolean;
    formatValue?: (v: number) => string | number;
    label?: string;
  }>(),
  {
    min: 0,
    max: 100,
    step: 1,
    modelValue: undefined,
    range: false,
    disabled: false,
    size: "md",
    marks: undefined,
    showValue: false,
    formatValue: (v: number) => v,
    label: "",
  }
);

const emit = defineEmits<{
  (e: "update:modelValue", value: SliderValue): void;
  (e: "changeEnd", value: SliderValue): void;
}>();

const trackRef = ref<HTMLDivElement | null>(null);
const dragIndex = ref<number | null>(null);

const current = computed<SliderValue>(() =>
  props.modelValue != null ? props.modelValue : props.range ? [props.min, props.max] : props.min
);
const vals = computed<number[]>(() =>
  props.range ? (current.value as [number, number]) : [current.value as number]
);

const clamp = (v: number) => Math.min(props.max, Math.max(props.min, v));
const roundStep = (v: number) =>
  clamp(Number((Math.round((v - props.min) / props.step) * props.step + props.min).toFixed(10)));
const pct = (v: number) => ((v - props.min) / (props.max - props.min)) * 100;

function applyThumb(i: number, v: number, end: boolean) {
  let next: SliderValue;
  if (props.range) {
    const [lo = props.min, hi = props.max] = vals.value;
    next = i === 0 ? [Math.min(v, hi), hi] : [lo, Math.max(v, lo)];
  } else {
    next = v;
  }
  emit("update:modelValue", next);
  if (end) emit("changeEnd", next);
}

function valueFromClient(clientX: number) {
  const rect = trackRef.value!.getBoundingClientRect();
  const ratio = Math.min(1, Math.max(0, (clientX - rect.left) / rect.width));
  return roundStep(props.min + ratio * (props.max - props.min));
}

function startDrag(i: number, clientX: number) {
  dragIndex.value = i;
  applyThumb(i, valueFromClient(clientX), false);
  const move = (ev: PointerEvent) => applyThumb(dragIndex.value!, valueFromClient(ev.clientX), false);
  const up = (ev: PointerEvent) => {
    applyThumb(dragIndex.value!, valueFromClient(ev.clientX), true);
    dragIndex.value = null;
    window.removeEventListener("pointermove", move);
    window.removeEventListener("pointerup", up);
  };
  window.addEventListener("pointermove", move);
  window.addEventListener("pointerup", up);
}

function onTrackPointerDown(e: PointerEvent) {
  if (props.disabled) return;
  const v = valueFromClient(e.clientX);
  const [lo = props.min, hi = props.max] = vals.value;
  const i = props.range ? (Math.abs(lo - v) <= Math.abs(hi - v) ? 0 : 1) : 0;
  startDrag(i, e.clientX);
}

function onThumbPointerDown(i: number, e: PointerEvent) {
  // Grab this specific thumb (don't let the track re-pick by proximity —
  // matters when two range thumbs overlap), then start dragging it.
  if (props.disabled) return;
  (e.currentTarget as HTMLElement).focus();
  startDrag(i, e.clientX);
}

function onThumbKeyDown(i: number, e: KeyboardEvent) {
  if (props.disabled) return;
  const cur = vals.value[i];
  if (cur == null) return;
  const big = props.step * 10;
  let v = cur;
  switch (e.key) {
    case "ArrowRight":
    case "ArrowUp":
      v = cur + props.step;
      break;
    case "ArrowLeft":
    case "ArrowDown":
      v = cur - props.step;
      break;
    case "PageUp":
      v = cur + big;
      break;
    case "PageDown":
      v = cur - big;
      break;
    case "Home":
      v = props.min;
      break;
    case "End":
      v = props.max;
      break;
    default:
      return;
  }
  e.preventDefault();
  applyThumb(i, roundStep(v), true);
}

const fillStyle = computed(() => {
  const [lo = props.min, hi = props.max] = vals.value;
  return props.range
    ? { left: `${pct(lo)}%`, right: `${100 - pct(hi)}%` }
    : { left: "0", width: `${pct(lo)}%` };
});

const valueText = computed(() => {
  const [lo = props.min, hi = props.max] = vals.value;
  return props.range
    ? `${props.formatValue(lo)} – ${props.formatValue(hi)}`
    : `${props.formatValue(lo)}`;
});

const normalizedMarks = computed(() =>
  (props.marks ?? []).map((m) => (typeof m === "object" ? m : { value: m, label: String(m) }))
);
</script>

<template>
  <div class="jl-slider" :class="[`jl-slider--${props.size}`, props.disabled ? 'jl-slider--disabled' : '']">
    <div v-if="props.label || props.showValue" class="jl-slider__head">
      <span v-if="props.label" class="jl-slider__label">{{ props.label }}</span>
      <span v-if="props.showValue" class="jl-slider__value">{{ valueText }}</span>
    </div>
    <div ref="trackRef" class="jl-slider__track" @pointerdown="onTrackPointerDown">
      <span class="jl-slider__fill" :style="fillStyle" />
      <button
        v-for="(v, i) in vals"
        :key="i"
        type="button"
        class="jl-slider__thumb"
        :style="{ left: `${pct(v)}%` }"
        role="slider"
        :aria-valuemin="props.min"
        :aria-valuemax="props.max"
        :aria-valuenow="v"
        :aria-disabled="props.disabled || undefined"
        :tabindex="props.disabled ? -1 : 0"
        @keydown="onThumbKeyDown(i, $event)"
        @pointerdown.stop="onThumbPointerDown(i, $event)"
        @click.prevent
      />
    </div>
    <div v-if="normalizedMarks.length" class="jl-slider__marks">
      <span
        v-for="(m, i) in normalizedMarks"
        :key="i"
        class="jl-slider__mark"
        :style="{ left: `${pct(m.value)}%` }"
      >{{ m.label }}</span>
    </div>
  </div>
</template>

<style src="./slider.css"></style>

// registry/components/slider/react/slider.tsx
import * as React from "react";
import "./slider.css";

export type SliderMark = number | { value: number; label: React.ReactNode };
export type SliderSize = "sm" | "md" | "lg";
export type SliderValue = number | [number, number];

export interface SliderProps {
  min?: number;
  max?: number;
  step?: number;
  value?: SliderValue;
  defaultValue?: SliderValue;
  range?: boolean;
  onChange?: (value: SliderValue) => void;
  onChangeEnd?: (value: SliderValue) => void;
  disabled?: boolean;
  size?: SliderSize;
  marks?: SliderMark[];
  showValue?: boolean;
  formatValue?: (v: number) => React.ReactNode;
  label?: React.ReactNode;
  className?: string;
}

export function Slider({
  min = 0,
  max = 100,
  step = 1,
  value,
  defaultValue,
  range = false,
  onChange,
  onChangeEnd,
  disabled = false,
  size = "md",
  marks,
  showValue = false,
  formatValue = (v) => v,
  label,
  className = "",
}: SliderProps) {
  const isControlled = value != null;
  const initial: SliderValue =
    defaultValue != null ? defaultValue : range ? [min, max] : min;
  const [internal, setInternal] = React.useState<SliderValue>(initial);
  const current = isControlled ? (value as SliderValue) : internal;
  const vals = (range ? (current as [number, number]) : [current as number]) as number[];

  const trackRef = React.useRef<HTMLDivElement>(null);
  const valsRef = React.useRef<number[]>(vals);
  React.useEffect(() => {
    valsRef.current = vals;
  });
  const dragRef = React.useRef<number | null>(null);

  const clamp = (v: number) => Math.min(max, Math.max(min, v));
  const roundStep = (v: number) =>
    clamp(Number((Math.round((v - min) / step) * step + min).toFixed(10)));
  const pct = (v: number) => ((v - min) / (max - min)) * 100;

  const commit = (next: SliderValue, end: boolean) => {
    if (!isControlled) setInternal(next);
    if (onChange) onChange(next);
    if (end && onChangeEnd) onChangeEnd(next);
  };

  const applyThumb = (i: number, v: number, end: boolean) => {
    const cur = valsRef.current;
    let next: SliderValue;
    if (range) {
      const arr = [...cur];
      if (i === 0) arr[0] = Math.min(v, cur[1]);
      else arr[1] = Math.max(v, cur[0]);
      next = [arr[0], arr[1]];
    } else {
      next = v;
    }
    valsRef.current = range ? (next as [number, number]) : [next as number];
    commit(next, end);
  };

  const valueFromClient = (clientX: number) => {
    const rect = trackRef.current!.getBoundingClientRect();
    const ratio = Math.min(1, Math.max(0, (clientX - rect.left) / rect.width));
    return roundStep(min + ratio * (max - min));
  };

  const startDrag = (i: number, clientX: number) => {
    dragRef.current = i;
    applyThumb(i, valueFromClient(clientX), false);
    const move = (ev: PointerEvent) =>
      applyThumb(dragRef.current!, valueFromClient(ev.clientX), false);
    const up = (ev: PointerEvent) => {
      applyThumb(dragRef.current!, valueFromClient(ev.clientX), true);
      dragRef.current = null;
      window.removeEventListener("pointermove", move);
      window.removeEventListener("pointerup", up);
    };
    window.addEventListener("pointermove", move);
    window.addEventListener("pointerup", up);
  };

  const onTrackPointerDown = (e: React.PointerEvent) => {
    if (disabled) return;
    const v = valueFromClient(e.clientX);
    const cur = valsRef.current;
    const i = range ? (Math.abs(cur[0] - v) <= Math.abs(cur[1] - v) ? 0 : 1) : 0;
    startDrag(i, e.clientX);
  };

  const onThumbPointerDown = (i: number) => (e: React.PointerEvent<HTMLButtonElement>) => {
    // Grab this specific thumb (don't let the track re-pick by proximity —
    // matters when two range thumbs overlap), then start dragging it.
    if (disabled) return;
    e.stopPropagation();
    e.currentTarget.focus();
    startDrag(i, e.clientX);
  };

  const onThumbKeyDown = (i: number) => (e: React.KeyboardEvent) => {
    if (disabled) return;
    const cur = valsRef.current[i];
    const big = step * 10;
    let v: number;
    switch (e.key) {
      case "ArrowRight":
      case "ArrowUp":
        v = cur + step;
        break;
      case "ArrowLeft":
      case "ArrowDown":
        v = cur - step;
        break;
      case "PageUp":
        v = cur + big;
        break;
      case "PageDown":
        v = cur - big;
        break;
      case "Home":
        v = min;
        break;
      case "End":
        v = max;
        break;
      default:
        return;
    }
    e.preventDefault();
    applyThumb(i, roundStep(v), true);
  };

  const fillStyle: React.CSSProperties = range
    ? { left: `${pct(vals[0])}%`, right: `${100 - pct(vals[1])}%` }
    : { left: 0, width: `${pct(vals[0])}%` };

  const cls = [
    "jl-slider",
    `jl-slider--${size}`,
    disabled ? "jl-slider--disabled" : "",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const valueText = range
    ? `${formatValue(vals[0])} – ${formatValue(vals[1])}`
    : `${formatValue(vals[0])}`;

  return (
    <div className={cls}>
      {(label || showValue) && (
        <div className="jl-slider__head">
          {label && <span className="jl-slider__label">{label}</span>}
          {showValue && <span className="jl-slider__value">{valueText}</span>}
        </div>
      )}
      <div className="jl-slider__track" ref={trackRef} onPointerDown={onTrackPointerDown}>
        <span className="jl-slider__fill" style={fillStyle} />
        {vals.map((v, i) => (
          <button
            key={i}
            type="button"
            className="jl-slider__thumb"
            style={{ left: `${pct(v)}%` }}
            role="slider"
            aria-valuemin={min}
            aria-valuemax={max}
            aria-valuenow={v}
            aria-label={
              label ? `${label}${range ? ` ${i === 0 ? "minimum" : "maximum"}` : ""}` : undefined
            }
            aria-disabled={disabled || undefined}
            tabIndex={disabled ? -1 : 0}
            onKeyDown={onThumbKeyDown(i)}
            onPointerDown={onThumbPointerDown(i)}
            onClick={(e) => e.preventDefault()}
          />
        ))}
      </div>
      {marks && marks.length > 0 && (
        <div className="jl-slider__marks">
          {marks.map((m, i) => {
            const mv = typeof m === "object" ? m.value : m;
            const ml = typeof m === "object" ? m.label : m;
            return (
              <span key={i} className="jl-slider__mark" style={{ left: `${pct(mv)}%` }}>
                {ml}
              </span>
            );
          })}
        </div>
      )}
    </div>
  );
}
