// registry/components/timeline/react/timeline.tsx
import * as React from "react";
import "./timeline.css";

export type TimelineTone = "accent" | "success" | "warning" | "danger" | "info" | "muted";
export type TimelineSize = "sm" | "md";

export interface TimelineItemData {
  id?: string | number;
  title?: React.ReactNode;
  time?: React.ReactNode;
  description?: React.ReactNode;
  tone?: TimelineTone;
  icon?: React.ReactNode;
  /** Extra content rendered below the description. */
  children?: React.ReactNode;
}

export interface TimelineProps extends React.HTMLAttributes<HTMLOListElement> {
  /** Data-driven entries. Omit when composing with <Timeline.Item>. */
  items?: TimelineItemData[];
  size?: TimelineSize;
}

export interface TimelineItemProps extends Omit<React.LiHTMLAttributes<HTMLLIElement>, "title"> {
  title?: React.ReactNode;
  time?: React.ReactNode;
  description?: React.ReactNode;
  tone?: TimelineTone;
  icon?: React.ReactNode;
}

interface TimelineComponent extends React.FC<TimelineProps> {
  Item: React.FC<TimelineItemProps>;
}

const TimelineItem: React.FC<TimelineItemProps> = ({
  title,
  time,
  description,
  tone = "muted",
  icon,
  children,
  ...rest
}) => {
  const plain = !icon;
  return (
    <li className="jl-timeline__item" {...rest}>
      <div className="jl-timeline__rail">
        <span className="jl-timeline__dot" data-tone={tone} data-plain={plain || undefined} aria-hidden="true">
          {icon}
        </span>
        <span className="jl-timeline__line" aria-hidden="true" />
      </div>
      <div className="jl-timeline__body">
        <div className="jl-timeline__head">
          {title != null && <span className="jl-timeline__title">{title}</span>}
          {time != null && <span className="jl-timeline__time">{time}</span>}
        </div>
        {description != null && <div className="jl-timeline__desc">{description}</div>}
        {children != null && <div className="jl-timeline__extra">{children}</div>}
      </div>
    </li>
  );
};
TimelineItem.displayName = "Timeline.Item";

const Timeline = (({ items = [], size = "md", className = "", children, ...rest }: TimelineProps) => {
  const cls = ["jl-timeline", size === "sm" ? "jl-timeline--sm" : "", className].filter(Boolean).join(" ");

  // Composable form: <Timeline><Timeline.Item .../></Timeline>
  // The last item's connector line is hidden via CSS (:last-child), so children render as-is.
  if (children != null) {
    return (
      <ol className={cls} {...rest}>
        {children}
      </ol>
    );
  }

  return (
    <ol className={cls} {...rest}>
      {items.map((it, i) => (
        <TimelineItem
          key={it.id ?? i}
          title={it.title}
          time={it.time}
          description={it.description}
          tone={it.tone}
          icon={it.icon}
        >
          {it.children}
        </TimelineItem>
      ))}
    </ol>
  );
}) as TimelineComponent;

Timeline.displayName = "Timeline";
Timeline.Item = TimelineItem;

export { Timeline };

// registry/components/timeline/vue/Timeline.vue
<script setup lang="ts">
import { computed } from "vue";

type TimelineTone = "accent" | "success" | "warning" | "danger" | "info" | "muted";
type TimelineSize = "sm" | "md";

interface TimelineItemData {
  id?: string | number;
  title?: string;
  time?: string;
  description?: string;
  tone?: TimelineTone;
}

const props = withDefaults(
  defineProps<{
    /** Data-driven entries. Omit when composing with <TimelineItem>. */
    items?: TimelineItemData[];
    size?: TimelineSize;
  }>(),
  { items: () => [], size: "md" }
);

const cls = computed(() => ["jl-timeline", props.size === "sm" ? "jl-timeline--sm" : ""].filter(Boolean));
</script>

<template>
  <ol class="jl-timeline" :class="cls">
    <slot>
      <li v-for="(it, i) in props.items" :key="it.id ?? i" class="jl-timeline__item">
        <div class="jl-timeline__rail">
          <span class="jl-timeline__dot" :data-tone="it.tone || 'muted'" data-plain="true" aria-hidden="true" />
          <span class="jl-timeline__line" aria-hidden="true" />
        </div>
        <div class="jl-timeline__body">
          <div class="jl-timeline__head">
            <span v-if="it.title != null" class="jl-timeline__title">{{ it.title }}</span>
            <span v-if="it.time != null" class="jl-timeline__time">{{ it.time }}</span>
          </div>
          <div v-if="it.description != null" class="jl-timeline__desc">{{ it.description }}</div>
        </div>
      </li>
    </slot>
  </ol>
</template>

<style src="./timeline.css"></style>
