// registry/components/scroll-area/react/scroll-area.tsx
import * as React from "react";
import "./scroll-area.css";

export interface ScrollAreaProps extends React.HTMLAttributes<HTMLDivElement> {
  axis?: "x" | "y" | "both";
  maxHeight?: number | string;
  fade?: boolean;
  fadeColor?: string;
  viewportRef?:
    | React.Ref<HTMLDivElement>
    | ((node: HTMLDivElement | null) => void);
}

function assignRef(
  ref: ScrollAreaProps["viewportRef"],
  node: HTMLDivElement | null
) {
  if (typeof ref === "function") ref(node);
  else if (ref) (ref as React.MutableRefObject<HTMLDivElement | null>).current = node;
}

export function ScrollArea({
  axis = "y",
  maxHeight,
  fade = false,
  fadeColor,
  className = "",
  style,
  viewportRef,
  onScroll,
  children,
  ...rest
}: ScrollAreaProps) {
  const innerRef = React.useRef<HTMLDivElement | null>(null);
  const [edges, setEdges] = React.useState({ top: false, bottom: false });

  const setRef = React.useCallback(
    (node: HTMLDivElement | null) => {
      innerRef.current = node;
      assignRef(viewportRef, node);
    },
    [viewportRef]
  );

  const update = React.useCallback(() => {
    const el = innerRef.current;
    if (!el || !fade) return;
    const { scrollTop, scrollHeight, clientHeight } = el;
    setEdges({
      top: scrollTop > 1,
      bottom: scrollTop + clientHeight < scrollHeight - 1,
    });
  }, [fade]);

  React.useEffect(() => {
    if (!fade) return;
    update();
    const el = innerRef.current;
    if (!el) return;
    const ro = new ResizeObserver(update);
    ro.observe(el);
    if (el.firstElementChild) ro.observe(el.firstElementChild);
    return () => ro.disconnect();
  }, [fade, update]);

  const handleScroll = (e: React.UIEvent<HTMLDivElement>) => {
    if (fade) update();
    onScroll?.(e);
  };

  const cls = ["jl-scrollarea", `jl-scrollarea--${axis}`, className].filter(Boolean).join(" ");
  const rootStyle: React.CSSProperties = { ...style };
  if (fadeColor) (rootStyle as Record<string, string>)["--_fade-bg"] = fadeColor;

  return (
    <div
      className={cls}
      style={rootStyle}
      data-fade-top={fade && edges.top ? "true" : undefined}
      data-fade-bottom={fade && edges.bottom ? "true" : undefined}
      {...rest}
    >
      {fade && <div className="jl-scrollarea__fade jl-scrollarea__fade--top" />}
      <div
        ref={setRef}
        className="jl-scrollarea__viewport"
        style={maxHeight != null ? { maxHeight } : undefined}
        onScroll={handleScroll}
      >
        {children}
      </div>
      {fade && <div className="jl-scrollarea__fade jl-scrollarea__fade--bottom" />}
    </div>
  );
}

// registry/components/scroll-area/vue/ScrollArea.vue
<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount, watch, type CSSProperties } from "vue";

const props = withDefaults(
  defineProps<{
    axis?: "x" | "y" | "both";
    maxHeight?: number | string;
    fade?: boolean;
    fadeColor?: string;
  }>(),
  { axis: "y", maxHeight: undefined, fade: false, fadeColor: undefined }
);

const emit = defineEmits<{ (e: "scroll", ev: Event): void }>();

const viewport = ref<HTMLDivElement | null>(null);
const edges = ref({ top: false, bottom: false });
let ro: ResizeObserver | null = null;

function update() {
  const el = viewport.value;
  if (!el || !props.fade) return;
  const { scrollTop, scrollHeight, clientHeight } = el;
  edges.value = {
    top: scrollTop > 1,
    bottom: scrollTop + clientHeight < scrollHeight - 1,
  };
}

function handleScroll(ev: Event) {
  if (props.fade) update();
  emit("scroll", ev);
}

function setup() {
  teardown();
  if (!props.fade) return;
  update();
  const el = viewport.value;
  if (!el) return;
  ro = new ResizeObserver(update);
  ro.observe(el);
  if (el.firstElementChild) ro.observe(el.firstElementChild);
}

function teardown() {
  if (ro) {
    ro.disconnect();
    ro = null;
  }
}

onMounted(setup);
onBeforeUnmount(teardown);
watch(() => props.fade, setup);

defineExpose({ viewport });

const cls = computed(() => ["jl-scrollarea", `jl-scrollarea--${props.axis}`].join(" "));
const rootStyle = computed<CSSProperties>(() =>
  props.fadeColor ? ({ "--_fade-bg": props.fadeColor } as CSSProperties) : {}
);
const viewportStyle = computed<CSSProperties | undefined>(() =>
  props.maxHeight != null ? { maxHeight: props.maxHeight } : undefined
);
</script>

<template>
  <div
    :class="cls"
    :style="rootStyle"
    :data-fade-top="fade && edges.top ? 'true' : undefined"
    :data-fade-bottom="fade && edges.bottom ? 'true' : undefined"
  >
    <div v-if="fade" class="jl-scrollarea__fade jl-scrollarea__fade--top" />
    <div ref="viewport" class="jl-scrollarea__viewport" :style="viewportStyle" @scroll="handleScroll">
      <slot />
    </div>
    <div v-if="fade" class="jl-scrollarea__fade jl-scrollarea__fade--bottom" />
  </div>
</template>

<style src="./scroll-area.css"></style>
