// demo/react/src/components/ui/field/field.tsx
import * as React from "react";
import "./field.css";

export interface FieldProps {
  label?: React.ReactNode;
  hint?: React.ReactNode;
  error?: React.ReactNode;
  required?: boolean;
  optional?: boolean;
  htmlFor?: string;
  className?: string;
  children?: React.ReactNode;
}

export function Field({
  label,
  hint,
  error,
  required = false,
  optional = false,
  htmlFor,
  className = "",
  children,
}: FieldProps) {
  return (
    <div className={["jl-field", className].filter(Boolean).join(" ")}>
      {label && (
        <label className="jl-field__label" htmlFor={htmlFor}>
          {label}
          {required && (
            <span className="jl-field__req" aria-hidden="true">
              *
            </span>
          )}
          {optional && <span className="jl-field__optional">(optional)</span>}
        </label>
      )}
      {children}
      {error ? (
        <div className="jl-field__error" role="alert">
          {error}
        </div>
      ) : (
        hint && <div className="jl-field__hint">{hint}</div>
      )}
    </div>
  );
}

// registry/components/field/vue/Field.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    label?: string;
    hint?: string;
    error?: string;
    required?: boolean;
    optional?: boolean;
    htmlFor?: string;
  }>(),
  { required: false, optional: false }
);
</script>

<template>
  <div class="jl-field">
    <label v-if="label" class="jl-field__label" :for="htmlFor">
      {{ label }}
      <span v-if="required" class="jl-field__req" aria-hidden="true">*</span>
      <span v-if="optional" class="jl-field__optional">(optional)</span>
    </label>
    <slot />
    <div v-if="error" class="jl-field__error" role="alert">{{ error }}</div>
    <div v-else-if="hint" class="jl-field__hint">{{ hint }}</div>
  </div>
</template>

<style src="./field.css"></style>
