// registry/components/stepper/vue/Stepper.vue
<script setup lang="ts">
import { computed } from "vue";

type Step = string | { label: string; description?: string };

const props = withDefaults(
  defineProps<{
    steps: Step[];
    active?: number;
    orientation?: "horizontal" | "vertical";
    size?: "sm" | "md";
    clickable?: boolean;
  }>(),
  { active: 0, orientation: "horizontal", size: "md", clickable: false }
);

const emit = defineEmits<{ (e: "step-click", index: number, step: Step): void }>();

const norm = computed(() =>
  props.steps.map((s) => (typeof s === "string" ? { label: s } : s))
);

function stateOf(i: number) {
  return i < props.active ? "completed" : i === props.active ? "current" : "upcoming";
}

function onStepClick(i: number) {
  if (!props.clickable) return;
  const s = props.steps[i];
  if (s) emit("step-click", i, s);
}

const cls = computed(() =>
  [
    "jl-stepper",
    `jl-stepper--${props.orientation}`,
    props.size === "sm" ? "jl-stepper--sm" : "",
  ]
    .filter(Boolean)
    .join(" ")
);
</script>

<template>
  <ol :class="cls">
    <li v-for="(s, i) in norm" :key="i" class="jl-step" :data-state="stateOf(i)">
      <div class="jl-step__indicator">
        <component
          :is="clickable ? 'button' : 'span'"
          class="jl-step__marker"
          :type="clickable ? 'button' : undefined"
          :aria-current="stateOf(i) === 'current' ? 'step' : undefined"
          @click="onStepClick(i)"
        >
          <svg v-if="stateOf(i) === 'completed'" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M20 6 9 17l-5-5" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" /></svg>
          <template v-else>{{ i + 1 }}</template>
        </component>
        <span v-if="i < norm.length - 1" class="jl-step__line" aria-hidden="true" />
      </div>
      <div class="jl-step__body">
        <div class="jl-step__label">{{ s.label }}</div>
        <div v-if="s.description" class="jl-step__desc">{{ s.description }}</div>
      </div>
    </li>
  </ol>
</template>

<style src="./stepper.css"></style>

// registry/components/stepper/react/stepper.tsx
import * as React from "react";
import "./stepper.css";

export type Step =
  | string
  | {
      label: React.ReactNode;
      description?: React.ReactNode;
      icon?: React.ReactNode;
    };

export interface StepperProps extends React.OlHTMLAttributes<HTMLOListElement> {
  steps: Step[];
  active?: number;
  orientation?: "horizontal" | "vertical";
  size?: "sm" | "md";
  onStepClick?: (index: number, step: Step) => void;
}

const CHECK = (
  <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
    <path d="M20 6 9 17l-5-5" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);

export function Stepper({
  steps = [],
  active = 0,
  orientation = "horizontal",
  size = "md",
  onStepClick,
  className = "",
  ...rest
}: StepperProps) {
  const norm = steps.map((s) => (typeof s === "string" ? { label: s } : s));
  const cls = [
    "jl-stepper",
    `jl-stepper--${orientation}`,
    size === "sm" ? "jl-stepper--sm" : "",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <ol className={cls} {...rest}>
      {norm.map((s, i) => {
        const state = i < active ? "completed" : i === active ? "current" : "upcoming";
        const isLast = i === norm.length - 1;
        const clickable = !!onStepClick;
        const markerContent = state === "completed" ? CHECK : (s as { icon?: React.ReactNode }).icon ?? i + 1;
        const markerProps = {
          className: "jl-step__marker",
          "aria-current": state === "current" ? ("step" as const) : undefined,
        };
        return (
          <li className="jl-step" data-state={state} key={i}>
            <div className="jl-step__indicator">
              {clickable ? (
                <button type="button" {...markerProps} onClick={() => onStepClick(i, steps[i])}>
                  {markerContent}
                </button>
              ) : (
                <span {...markerProps}>{markerContent}</span>
              )}
              {!isLast && <span className="jl-step__line" aria-hidden="true" />}
            </div>
            <div className="jl-step__body">
              <div className="jl-step__label">{s.label}</div>
              {s.description && <div className="jl-step__desc">{s.description}</div>}
            </div>
          </li>
        );
      })}
    </ol>
  );
}
