// registry/components/radio-group/vue/RadioGroup.vue
<script setup lang="ts">
import { computed } from "vue";

type RadioOption =
  | string
  | { value: string; label: string; description?: string; disabled?: boolean };

const props = withDefaults(
  defineProps<{
    name: string;
    modelValue?: string;
    options: RadioOption[];
    direction?: "column" | "row";
    disabled?: boolean;
  }>(),
  { modelValue: "", direction: "column", disabled: false }
);

const emit = defineEmits<{
  (e: "update:modelValue", value: string): void;
}>();

const normalized = computed(() =>
  props.options.map((o) => (typeof o === "string" ? { value: o, label: o } : o))
);
</script>

<template>
  <div
    class="jl-radiogroup"
    :class="props.direction === 'row' ? 'jl-radiogroup--row' : ''"
    role="radiogroup"
  >
    <label
      v-for="opt in normalized"
      :key="opt.value"
      class="jl-radio"
      :data-disabled="(props.disabled || opt.disabled) || undefined"
    >
      <input
        type="radio"
        class="jl-radio__input"
        :name="props.name"
        :value="opt.value"
        :checked="props.modelValue === opt.value"
        :disabled="props.disabled || opt.disabled"
        @change="emit('update:modelValue', opt.value)"
      />
      <span class="jl-radio__dot" />
      <span class="jl-radio__body">
        <span class="jl-radio__label">{{ opt.label }}</span>
        <span v-if="opt.description" class="jl-radio__desc">{{ opt.description }}</span>
      </span>
    </label>
  </div>
</template>

<style src="./radio-group.css"></style>

// demo/react/src/components/ui/radio-group/radio-group.tsx
import * as React from "react";
import "./radio-group.css";

export type RadioOption =
  | string
  | {
      value: string;
      label: React.ReactNode;
      description?: React.ReactNode;
      disabled?: boolean;
    };

export interface RadioGroupProps {
  /** Shared input name. */
  name: string;
  /** Currently selected value (controlled). */
  value?: string;
  onChange?: (value: string, event: React.ChangeEvent<HTMLInputElement>) => void;
  options: RadioOption[];
  /** Stack vertically or inline. @default "column" */
  direction?: "column" | "row";
  disabled?: boolean;
  className?: string;
}

export function RadioGroup({
  name,
  value,
  onChange,
  options = [],
  direction = "column",
  disabled = false,
  className = "",
}: RadioGroupProps) {
  return (
    <div
      className={[
        "jl-radiogroup",
        direction === "row" ? "jl-radiogroup--row" : "",
        className,
      ]
        .filter(Boolean)
        .join(" ")}
      role="radiogroup"
    >
      {options.map((o) => {
        const opt = typeof o === "string" ? { value: o, label: o } : o;
        const isDisabled = disabled || ("disabled" in opt && opt.disabled);
        return (
          <label key={opt.value} className="jl-radio" data-disabled={isDisabled || undefined}>
            <input
              type="radio"
              className="jl-radio__input"
              name={name}
              value={opt.value}
              checked={value === opt.value}
              disabled={isDisabled}
              onChange={(e) => onChange && onChange(e.target.value, e)}
            />
            <span className="jl-radio__dot" />
            <span className="jl-radio__body">
              <span className="jl-radio__label">{opt.label}</span>
              {"description" in opt && opt.description && (
                <span className="jl-radio__desc">{opt.description}</span>
              )}
            </span>
          </label>
        );
      })}
    </div>
  );
}
