// registry/components/dialog/react/dialog.tsx
import * as React from "react";
import "./dialog.css";

export interface DialogProps {
  open: boolean;
  onClose?: () => void;
  title?: React.ReactNode;
  description?: React.ReactNode;
  size?: "sm" | "md" | "lg";
  /** Below --bp-mobile, render as a bottom sheet ("sheet", default) or stay centered ("center"). */
  mobile?: "sheet" | "center";
  footer?: React.ReactNode;
  showClose?: boolean;
  className?: string;
  children?: React.ReactNode;
}

export function Dialog({
  open,
  onClose,
  title,
  description,
  size = "md",
  mobile = "sheet",
  footer,
  showClose = true,
  className = "",
  children,
}: DialogProps) {
  React.useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose?.();
    };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [open, onClose]);

  if (!open) return null;

  return (
    <div
      className="jl-dialog__overlay"
      data-mobile={mobile}
      onMouseDown={(e) => {
        if (e.target === e.currentTarget) onClose?.();
      }}
    >
      <div
        className={["jl-dialog", `jl-dialog--${size}`, className].filter(Boolean).join(" ")}
        role="dialog"
        aria-modal="true"
      >
        {(title || showClose) && (
          <div className="jl-dialog__header">
            <div className="jl-dialog__header-text">
              {title && <div className="jl-dialog__title">{title}</div>}
              {description && <div className="jl-dialog__desc">{description}</div>}
            </div>
            {showClose && (
              <button type="button" className="jl-dialog__close" aria-label="Close" onClick={onClose}>
                <svg viewBox="0 0 18 18" width="18" height="18" fill="none" aria-hidden="true">
                  <path d="M5 5l8 8M13 5l-8 8" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" />
                </svg>
              </button>
            )}
          </div>
        )}
        {children && <div className="jl-dialog__body">{children}</div>}
        {footer && <div className="jl-dialog__footer">{footer}</div>}
      </div>
    </div>
  );
}

// registry/components/dialog/vue/Dialog.vue
<script setup lang="ts">
import { watch, onBeforeUnmount } from "vue";

const props = withDefaults(
  defineProps<{
    open: boolean;
    title?: string;
    description?: string;
    size?: "sm" | "md" | "lg";
    showClose?: boolean;
    /** Below --bp-mobile, render as a bottom sheet ("sheet", default) or stay centered ("center"). */
    mobile?: "sheet" | "center";
  }>(),
  { title: "", description: "", size: "md", showClose: true, mobile: "sheet" }
);

const emit = defineEmits<{ close: []; "update:open": [open: boolean] }>();

function close() {
  emit("close");
  emit("update:open", false);
}
function onKey(e: KeyboardEvent) {
  if (e.key === "Escape") close();
}
watch(
  () => props.open,
  (v) => {
    if (v) document.addEventListener("keydown", onKey);
    else document.removeEventListener("keydown", onKey);
  }
);
onBeforeUnmount(() => document.removeEventListener("keydown", onKey));
</script>

<template>
  <div v-if="open" class="jl-dialog__overlay" :data-mobile="mobile" @mousedown.self="close">
    <div :class="['jl-dialog', `jl-dialog--${size}`]" role="dialog" aria-modal="true">
      <div v-if="title || showClose" class="jl-dialog__header">
        <div class="jl-dialog__header-text">
          <div v-if="title" class="jl-dialog__title">{{ title }}</div>
          <div v-if="description" class="jl-dialog__desc">{{ description }}</div>
        </div>
        <button v-if="showClose" type="button" class="jl-dialog__close" aria-label="Close" @click="close">
          <svg viewBox="0 0 18 18" width="18" height="18" fill="none" aria-hidden="true">
            <path d="M5 5l8 8M13 5l-8 8" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" />
          </svg>
        </button>
      </div>
      <div v-if="$slots.default" class="jl-dialog__body"><slot /></div>
      <div v-if="$slots.footer" class="jl-dialog__footer"><slot name="footer" /></div>
    </div>
  </div>
</template>

<style src="./dialog.css"></style>
