// registry/components/page-header/vue/PageHeader.vue
<script setup lang="ts">
import { computed } from "vue";

const props = withDefaults(
  defineProps<{
    title?: string;
    description?: string;
    eyebrow?: string;
    back?: boolean;
    sticky?: boolean;
    variant?: "surface" | "plain";
    as?: string;
  }>(),
  {
    title: "",
    description: "",
    eyebrow: "",
    back: false,
    sticky: false,
    variant: "surface",
    as: "header",
  }
);

const emit = defineEmits<{ (e: "back"): void }>();

const cls = computed(() =>
  [
    "jl-pageheader",
    props.variant === "plain" ? "jl-pageheader--plain" : "jl-pageheader--surface",
    props.sticky ? "jl-pageheader--sticky" : "",
  ]
    .filter(Boolean)
    .join(" ")
);
</script>

<template>
  <component :is="as" :class="cls">
    <div v-if="$slots.breadcrumb" class="jl-pageheader__crumb"><slot name="breadcrumb" /></div>
    <div class="jl-pageheader__bar">
      <div v-if="$slots.leading || back" class="jl-pageheader__lead">
        <slot name="leading" />
        <button v-if="back" type="button" class="jl-pageheader__back" aria-label="Go back" @click="emit('back')">
          <svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m15 6-6 6 6 6" stroke="currentColor" stroke-width="1.85" stroke-linecap="round" stroke-linejoin="round" /></svg>
        </button>
      </div>
      <span v-if="$slots.icon" class="jl-pageheader__icon"><slot name="icon" /></span>
      <div class="jl-pageheader__heading">
        <div v-if="eyebrow || $slots.eyebrow" class="jl-pageheader__eyebrow"><slot name="eyebrow">{{ eyebrow }}</slot></div>
        <div class="jl-pageheader__titlerow">
          <h1 v-if="title || $slots.title" class="jl-pageheader__title"><slot name="title">{{ title }}</slot></h1>
          <slot />
        </div>
        <p v-if="description || $slots.description" class="jl-pageheader__desc"><slot name="description">{{ description }}</slot></p>
      </div>
      <div v-if="$slots.actions" class="jl-pageheader__actions"><slot name="actions" /></div>
    </div>
    <div v-if="$slots.tabs" class="jl-pageheader__tabs"><slot name="tabs" /></div>
  </component>
</template>

<style src="./page-header.css"></style>

// registry/components/page-header/react/page-header.tsx
import * as React from "react";
import "./page-header.css";

export interface PageHeaderProps
  extends Omit<React.HTMLAttributes<HTMLElement>, "title"> {
  title?: React.ReactNode;
  description?: React.ReactNode;
  eyebrow?: React.ReactNode;
  icon?: React.ReactNode;
  breadcrumb?: React.ReactNode;
  actions?: React.ReactNode;
  tabs?: React.ReactNode;
  leading?: React.ReactNode;
  onBack?: () => void;
  sticky?: boolean;
  variant?: "surface" | "plain";
  as?: React.ElementType;
}

export function PageHeader({
  title,
  description,
  eyebrow,
  icon = null,
  breadcrumb = null,
  actions = null,
  tabs = null,
  leading = null,
  onBack,
  sticky = false,
  variant = "surface",
  as,
  className = "",
  children,
  ...rest
}: PageHeaderProps) {
  const Tag = (as ?? "header") as React.ElementType;
  const cls = [
    "jl-pageheader",
    variant === "plain" ? "jl-pageheader--plain" : "jl-pageheader--surface",
    sticky ? "jl-pageheader--sticky" : "",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <Tag className={cls} {...rest}>
      {breadcrumb && <div className="jl-pageheader__crumb">{breadcrumb}</div>}
      <div className="jl-pageheader__bar">
        {(leading || onBack) && (
          <div className="jl-pageheader__lead">
            {leading}
            {onBack && (
              <button type="button" className="jl-pageheader__back" aria-label="Go back" onClick={onBack}>
                <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
                  <path d="m15 6-6 6 6 6" stroke="currentColor" strokeWidth="1.85" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </button>
            )}
          </div>
        )}
        {icon && <span className="jl-pageheader__icon">{icon}</span>}
        <div className="jl-pageheader__heading">
          {eyebrow && <div className="jl-pageheader__eyebrow">{eyebrow}</div>}
          <div className="jl-pageheader__titlerow">
            {title != null && <h1 className="jl-pageheader__title">{title}</h1>}
            {children}
          </div>
          {description && <p className="jl-pageheader__desc">{description}</p>}
        </div>
        {actions && <div className="jl-pageheader__actions">{actions}</div>}
      </div>
      {tabs && <div className="jl-pageheader__tabs">{tabs}</div>}
    </Tag>
  );
}
